concrete-npe/Cargo.toml
concrete-npe/src/lwe.rs
concrete/Cargo.toml
concrete/src/lib.rs

This patch fixes the issues reported in #9.

Hotfix/npe deltas #9

---

LICENSE
concrete-commons/LICENSE
concrete-commons/README.md
concrete-core/README.md
concrete-csprng/LICENSE
concrete-csprng/README.md
concrete-npe/LICENSE
concrete-npe/README.md
concrete/README.md

Fixes zama-ai/concrete_internal#100

fix(license): adds missing license files.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Signed-off-by: Agnes Leroy <agnes.leroy@zama.ai>
Resolves: zama-ai/concrete_internal#98

chore(templates): improve pr template and add issue templates

---

.github/workflows/aws_tests.yml
.github/workflows/build.yml
.github/workflows/build_benches.yml
.github/workflows/check_commit.yml
.github/workflows/doc.yml
.github/workflows/lint.yml
concrete-core/src/lib.rs
concrete-core/src/math/polynomial/polynomial.rs
grcov.yml

The workflows perform:
- lint with clippy
- check format with rustfmt
- build on Ubuntu and Max OS
- check commit message format
- check the PR references an issue
- build the doc (fail when links are broken)
- build the benches
- when applying the `aws_test` label to the PR, launches the tests on an AWS instance
Resolves zama-ai/concrete_internal#26 and zama-ai/concrete_internal#97
Signed-off-by: Agnes Leroy <agnes.leroy@zama.ai>

test(ci): add github actions workflows

---

README.md

Add an installation note for Apple M1 users

Add an installation note for Apple Silicon users

---

concrete-core/src/crypto/gsw/ciphertext.rs

fix(gsw): fix an overflow in gsw::external_product

---

README.md
concrete-commons/README.md
concrete-core/README.md
concrete-csprng/README.md
concrete-npe/README.md
concrete/README.md

Fix a small mistake in the README files
if you have any question -> if you have any questions

Fix mistake in the readme files

---

.github/pull_request_template.md

- Reorder sections
- Update the aws label from `aws_label` to `aws_test`
- Add checkbox requiring to check for breaking changes
- Add tip on how to link an issue

chore(ecosystem): update PR template.

---

README.md

Add a link to Zama community website in README
It doesn't but for a README fix like this I guess it's ok (Agnes guessing)

chore(ecosystem): add link to community in README

---

concrete-commons/src/numeric/float.rs
concrete-commons/src/numeric/unsigned.rs

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] The draft release description has been updated~~

fix(commons): apply `#[must_use]` attribute

---

concrete-boolean/docs/requirements.txt
concrete-core/docs/index.rst
concrete-core/docs/requirements.txt

Update documentation theme to latest version

docs: update theme to v2.2.0

---

concrete/src/lwe/mod.rs
concrete/src/lwe/tests.rs

~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] The draft release description has been updated~~

fix(concrete): fix a bug related to encoders in add_with_new_min_inplace

---

concrete-core/src/backends/core/private/crypto/secret/generators/encryption.rs

zama-ai/concrete_internal#282
When generating large bootstrap keys, we reach the bounds of the generator. This is due to the rejection sampling algorithm used to sample gaussian variates: We do not provision enough randomness to generate one sample (8*6) bytes. We now provision (8*32) bytes, which solves the issue.

fix(concrete_core): change gaussian sampling randomness provision

---

README.md

Update the readme file about windows support current state and how to contribute to the project.
~~[ ]Tests for the changes have been added (for bug fixes / features)~~
~~[ ] Docs have been added / updated (for bug fixes / features)~~
~~[ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
~~[ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~~
~~[ ] The draft release description has been updated~~
~~[ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~~
[conventional-breaking]: …

chore(readme): add contributing / no windows support

---

concrete-core/README.md

Add the link to the community post for the concrete-core-1.0.0-alpha release.

Update README for concrete-core

---

concrete-core/src/backends/core/private/crypto/bootstrap/fourier/mod.rs

- zama-ai/concrete_internal/issues/341

Replace StandardGgswCiphertext by FourierGgswCiphertext in the FourierBoostrapKey

---

README.md

Add Citing note for academic paper

chore(ecosystem): add citing note

---

concrete-core/src/backends/core/private/math/torus/mod.rs

- zama-ai/concrete_internal/issues/344

chore(concrete_core): Removes unnecessary constraints on UnsignedTorus.

---

concrete-boolean/docs/requirements.txt
concrete-boolean/docs/user/index.rst
concrete-core/docs/requirements.txt

Add new Tutorial from Optalysys to Boolean docs

docs(boolean): add encrypted search tutorial

---

concrete-core-fixture/src/fixture/lwe_ciphertext_vector_fusing_addition.rs
concrete-core-fixture/src/fixture/mod.rs
concrete-core-test/src/core.rs

test(core): add fixture & test for lwe_ciphertext_vector_fusing_addition

---

LICENSE
concrete-boolean/LICENSE
concrete-commons/LICENSE
concrete-core-fixture/LICENSE
concrete-core-test/LICENSE
concrete-core/LICENSE
concrete-csprng/LICENSE
concrete-npe/LICENSE
concrete/LICENSE

chore(ecosystem): update LICENSE

---

concrete-core/docs/dev/benchmarking_backends.md

docs(core): update benchmarking_backends.md

---

concrete-core/src/backends/core/private/math/decomposition/iter.rs
concrete-core/src/backends/core/private/math/decomposition/tests.rs

Refer to https://doi.org/10.1007/978-3-030-92078-4_19 for more details.
- zama-ai/concrete_internal/issues/71

Decomposition Algorithm

---

concrete-commons/src/parameters.rs
concrete-core/src/backends/core/private/crypto/bootstrap/fourier/mod.rs

- zama-ai/concrete_internal/issues/389

feat(concrete_core): Extends the Modulus Switching

---

concrete-core/docs/api/backends.md

docs(core): fix links to the rust doc in the user doc

---

concrete-core/src/backends/core/private/crypto/bootstrap/fourier/mod.rs
concrete-core/src/backends/core/private/crypto/bootstrap/fourier/tests.rs

I remove the old sample extract test (it was testing the sample extract implemented in the bootstrap). We'll add the sample extract as a public engine with its test in a later PR.

chore(core): refactor sample extract in private

---

INSTALL.md
README.md
concrete/docs/getting_started/installation.md
concrete/src/user_doc_tests.rs

docs(readme): add code sample and split install part

---

concrete-integer/benches/bench.rs
concrete-integer/src/crt/mod.rs
concrete-integer/src/server_key/crt.rs
concrete-integer/src/server_key/crt_parallel.rs
concrete-integer/src/server_key/mod.rs

adds multithreaded versions for crt operations

crt parallel

---

concrete-integer/benches/bench.rs
concrete-integer/src/server_key/add.rs
concrete-integer/src/server_key/add_parallel.rs
concrete-integer/src/server_key/bitwise_op.rs
concrete-integer/src/server_key/bitwise_op_parallel.rs
concrete-integer/src/server_key/mod.rs
concrete-integer/src/server_key/mul_parallel.rs
concrete-integer/src/server_key/neg_parallel.rs
concrete-integer/src/server_key/scalar_add_parallel.rs
concrete-integer/src/server_key/scalar_mul_parallel.rs
concrete-integer/src/server_key/scalar_sub_parallel.rs
concrete-integer/src/server_key/shift_parallel.rs
concrete-integer/src/server_key/sub_parallel.rs
concrete-integer/src/server_key/tests_parallel.rs

parallelizes integer radix operations using rayon

feat(integer): parallelize radix operations

---

README.md
concrete/docs/SUMMARY.md
concrete/docs/getting_started/installation.md
concrete/docs/getting_started/quick_start.md
concrete/docs/how_to/serialization.md
concrete/docs/tutorials/latin_string.md
concrete/docs/tutorials/parity_bit.md

docs(concrete): fix README badge address

---

concrete-integer/benches/bench.rs
concrete/src/shortints/types/static.rs

Addresses two lints from clippy as well as adding a missing implementation of Deserialize/Serialize.
Due to serde not supporting const generics with have to roll our own code

Add missing derive

---

README.md

chore(doc): add a transition warning in README

---

README.md
docs/README.md
docs/dev/compilation.md
docs/dev/contributing.md
docs/dev/terminology_and_structure.md
docs/getting-started/compatibility.md
docs/getting-started/exactness.md
docs/getting-started/installing.md
docs/getting-started/performance.md
docs/getting-started/quick_start.md
docs/howto/configure.md
docs/howto/debug.md
docs/howto/deploy.md
docs/tutorial/direct_circuits.md
docs/tutorial/extensions.md
docs/tutorial/floating_points.md
docs/tutorial/formatting.md
docs/tutorial/rounded_table_lookups.md
docs/tutorial/simulation.md
docs/tutorial/table_lookups.md
docs/tutorial/tagging.md

chore(frontend/python): doc fixes

---

backends/concrete-cpu/implementation/src/c_api/csprng.rs

feat(backend-cpu): use Apple secure enclave seeder on M1

---

backends/concrete-cuda/implementation/test_and_benchmark/benchmark/README.md
backends/concrete-cuda/implementation/test_and_benchmark/test/README.md

**Description:**
This PR improves the README.md related to the benchmark tool and introduces a new one for the test tool.

docs(backend-gpu): improve concrete-cuda docs regarding tests and benchmarks

---

compilers/concrete-compiler/compiler/Makefile
compilers/concrete-compiler/compiler/include/concretelang/Support/V0Parameters.h
compilers/concrete-compiler/compiler/tests/end_to_end_fixture/end_to_end_round_gen.py
compilers/concrete-compiler/compiler/tests/end_to_end_tests/end_to_end_test.h

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18dgDEBwE4GQIgssMazTRgdjDMfYLNRE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=OmI5Ryv)

bench(compiler): Add dag-multi strategy to bench 

---

compilers/concrete-compiler/.gitignore
compilers/concrete-compiler/compiler/.gitignore
compilers/concrete-compiler/compiler/Makefile

Fixes leftover from https://github.com/zama-ai/concrete/pull/354

chore(compiler): makefile and gitignore cleanup

---

backends/concrete-cuda/implementation/src/vertical_packing.cuh
backends/concrete-cuda/implementation/test_and_benchmark/setup_and_teardown.cpp
backends/concrete-cuda/implementation/test_and_benchmark/test/test_cmux_tree.cpp
backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp

Resolves https://github.com/zama-ai/concrete-internal/issues/248

fix(backend-gpu): fix cmux tree for tau > 1

---

.github/workflows/concrete_cuda_benchmark.yml
.github/workflows/concrete_cuda_test.yml
backends/concrete-cuda/implementation/include/vertical_packing.h
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bit_extraction.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bootstrap.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_circuit_bootstrap.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_cmux_tree.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_keyswitch.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_linear_algebra.cpp
backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_wop_bootstrap.cpp

Investigate why concrete-cuda ci fails

Concrete-cuda | fix ci

---

tools/parameter-curves/Makefile
tools/parameter-curves/README.rst
tools/parameter-curves/lattice-scripts/compare_curves_and_estimator.py
tools/parameter-curves/lattice-scripts/generate_data.py
tools/parameter-curves/lattice-scripts/verify_curves.py

Update README, remove some old comments, and add support to check a curve for a custom `log2(q)` value.

chore(param-curves): update files for parameter curves

---

compilers/concrete-compiler/compiler/lib/Dialect/FHE/Transforms/EncryptedMulToDoubleTLU.cpp

This commit adds a small doc comment on a topic that I had a few questions on.

chore(compiler): add code doc on encrypted mul

---

frontends/concrete-python/concrete/fhe/tracing/tracer.py
frontends/concrete-python/tests/execution/test_others.py

(closes https://github.com/zama-ai/concrete-internal/issues/243)

fix(frontend-python): support axis as a positional argument for np.expand_dims

---

compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHE/IR/FHEOps.td
compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHELinalg/IR/FHELinalgOps.td
compilers/concrete-compiler/compiler/lib/Dialect/FHE/IR/FHEOps.cpp
compilers/concrete-compiler/compiler/lib/Dialect/FHELinalg/IR/FHELinalgOps.cpp
compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHE/Analysis/MANP_linalg.mlir
compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHE/folding.mlir
compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/folding.mlir

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18LNc6186ejCXu8VSnLAlNWxxPDrx9jLg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-MF-02H)
That will close https://github.com/zama-ai/concrete-internal/issues/297 also for dag-multi optimization

fix(compiler): fold mul and matmul by zero tensor to zero tensor

---

frontends/concrete-python/concrete/fhe/compilation/compiler.py
frontends/concrete-python/concrete/fhe/tracing/tracer.py
frontends/concrete-python/tests/compilation/test_compiler.py
frontends/concrete-python/tests/execution/test_reshape.py
frontends/concrete-python/tests/execution/test_sum.py

Fix: Various Issues

---

UPGRADING.md

chore(common): update UPGRADING notes

---

compilers/concrete-compiler/compiler/include/concretelang/Dialect/TFHE/Analysis/ExtractStatistics.h
compilers/concrete-compiler/compiler/include/concretelang/Support/CompilationFeedback.h
compilers/concrete-compiler/compiler/include/concretelang/Support/Pipeline.h
compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/compilation_feedback.py
compilers/concrete-compiler/compiler/lib/Dialect/TFHE/Analysis/CMakeLists.txt
compilers/concrete-compiler/compiler/lib/Dialect/TFHE/Analysis/ExtractStatistics.cpp
compilers/concrete-compiler/compiler/lib/Dialect/TFHE/CMakeLists.txt
compilers/concrete-compiler/compiler/lib/Support/CMakeLists.txt
compilers/concrete-compiler/compiler/lib/Support/CompilationFeedback.cpp
compilers/concrete-compiler/compiler/lib/Support/CompilerEngine.cpp
compilers/concrete-compiler/compiler/lib/Support/Pipeline.cpp
docs/howto/configure.md
frontends/concrete-python/concrete/fhe/compilation/circuit.py
frontends/concrete-python/concrete/fhe/compilation/compiler.py
frontends/concrete-python/concrete/fhe/compilation/configuration.py
frontends/concrete-python/concrete/fhe/compilation/server.py
frontends/concrete-python/tests/compilation/test_circuit.py

CC @bcm-at-zama @andrei-stoian-zama
I'm not sure if this is the best place to do the analysis and whether we should analyze in FHE instead of TFHE for example. Let me know if you want to move the analysis to another time @youben11.

Feat: Statistics

---

backends/concrete-cuda/implementation/include/bootstrap_multibit.h
backends/concrete-cuda/implementation/src/crypto/bootstrapping_key.cuh
backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp
backends/concrete-cuda/rust_api/Cargo.toml
backends/concrete-cuda/rust_api/src/cuda_bind.rs

Minor adjustments to fix the visibility of the multi-bit PBS on the rust API. 
Also, increases the rust API version to v0.1.2.

fix(backend-gpu): minor fixes to the rust API

---

.github/workflows/concrete_ml_tests.yml
ci/scripts/test_cml.sh
ci/slab.toml

The PR doesn't cover when this should be ran, although, we should be able to run it manually, from main, or a specific PR, thanks to Slab.
AFAIK, new slab commands need to merged on main before we can make a test run.

ML tests with latest CP

---

frontends/concrete-python/concrete/fhe/representation/graph.py
frontends/concrete-python/tests/compilation/test_circuit.py

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX180RcRFgvV1Qaoj13Rb989c8a5vS5w4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=0WEJVud)

test(frontend-python): Remove the high p_error in graph evaluation tests

---

compilers/concrete-compiler/compiler/lib/Conversion/FHEToTFHECrt/FHEToTFHECrt.cpp

When using crt encoding, some fhe.zero op results will be converted to tensors (crt encoded eint), so should be converted to tfhe.zero_tensor operations instead of tfhe.zero

fix(compiler): lower fhe.zero to either scalar or tensor variant based on encoding

---

compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/__init__.py
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/compilation_options.py

Adding more compilation options from python

---

.github/workflows/concrete_ml_tests.yml
ci/scripts/test_cml.sh
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/compilation_feedback.py
compilers/concrete-compiler/compiler/tests/python/test_statistics.py

Fix: Regression

---

.github/workflows/main.yml
.github/workflows/markdown_link_check.yml
backends/concrete-cpu/implementation/README.md
backends/concrete-cuda/implementation/README.md
backends/concrete-cuda/implementation/test_and_benchmark/test/README.md
docs/README.md
docs/application-tutorial/game_of_life.md
docs/getting-started/compatibility.md
docs/howto/call_from_other_language.md

closes https://github.com/zama-ai/concrete-internal/issues/487

chore(ci): add markdown link check

---

.github/workflows/concrete_python_tests_linux.yml
.github/workflows/main.yml
ci/slab.toml
compilers/concrete-compiler/compiler/include/concretelang/Dialect/SDFG/IR/SDFGOps.td
compilers/concrete-compiler/compiler/include/concretelang/Runtime/stream_emulator_api.h
compilers/concrete-compiler/compiler/include/concretelang/Support/CompilerEngine.h
compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/compilation_options.py
compilers/concrete-compiler/compiler/lib/Conversion/ExtractSDFGOps/ExtractSDFGOps.cpp
compilers/concrete-compiler/compiler/lib/Conversion/SDFGToStreamEmulator/SDFGToStreamEmulator.cpp
compilers/concrete-compiler/compiler/lib/Runtime/GPUDFG.cpp
compilers/concrete-compiler/compiler/lib/Transforms/Batching.cpp
frontends/concrete-python/Makefile
frontends/concrete-python/concrete/fhe/compilation/configuration.py
frontends/concrete-python/concrete/fhe/compilation/server.py
frontends/concrete-python/tests/conftest.py

This PR enables GPU offload in CP, and fixes the various issues raised by the pytest-gpu tests in the GPU offloading runtime (SDFG dialect, batching and lowering & GPUDFG runtime).

Support for [Multi-]GPU in CP

---

frontends/concrete-python/tests/execution/test_min_max.py

related to multi output in multi parameter

fix(frontend-python): some tests are broken due to compiler bug

---

docs/application-tutorial/game_of_life.md
docs/dev/compilation/FHEDialect.md
docs/dev/compilation/FHELinalgDialect.md
docs/howto/call_from_other_language.md
docs/howto/configure.md
docs/howto/debug.md
docs/tutorial/bit_extraction.md
docs/tutorial/bitwise.md
docs/tutorial/comparisons.md
docs/tutorial/extensions.md
docs/tutorial/minmax.md
docs/tutorial/multi_parameters.md
docs/tutorial/statistics.md
docs/tutorial/workarounds.md

v2.4 -> v2.5 diff review for docs, included updated changes from #593

2.5 docs review

---

README.md

- Replace support banner 
- Add licence badge 
- Add "resources" link

chore(docs): update readme.md

---

README.md

- Reorganized existing content to follow the new structure
- Aligned all the header links and badges
- Added a table of contents
- Added a call-to-action for users to star the repo
- Checked all links and replaced outdated ones.
- Unified the formatting
- Updated the support banner
- Improved the overall content quality
- Added missing content where necessary
- Added more “resources” for each product
- Ensured wording is consistent throughout

docs: update Readme.md 

---

compilers/concrete-compiler/compiler/include/concretelang/Common/Keys.h
compilers/concrete-compiler/compiler/lib/Common/Keys.cpp
frontends/concrete-python/tests/conftest.py

fix(compiler): Guard decompression of seeded keys

---

docs/compilation/compression.md

fix(compiler): fix the compilation doc

---

docs/tutorials/see-all-tutorials.md

closes #https://github.com/zama-ai/concrete-internal/issues/682

docs(compiler): fix broken links

---

docs/explanations/security_curves.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1csJttpTdzXdfQqH3eWo4AB0SDsb6yW2M%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=EtIJ--Y)
close zama-ai/concrete-internal#649

docs(compiler): Add warnings about IND-CPA security model

---

frontends/concrete-python/examples/xor_distance/hamming_distance.py
frontends/concrete-python/examples/xor_distance/xor_distance.md

docs(compiler): fix a typo

---

frontends/concrete-python/examples/xor_distance/hamming_distance.py

as per @umut-sahin, https://zama-ai.slack.com/archives/C02GKTQ2BLG/p1713448341845479?thread_ts=1713430715.409709&cid=C02GKTQ2BLG

Improve xor distance example

---

frontends/concrete-python/Makefile

A real fix should be done but until then, no need to open the gates for more uncovered code.

chore(frontend-python): requires 99% coverage

---

.github/workflows/concrete_python_release.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1GsgRJrW8f4Y8ZRoGH8DLaalkhl8Gvc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2eGKZAg)

fix(ci): use GITHUB_TOKEN for workflow dispatch

---

compilers/concrete-compiler/compiler/include/concretelang/Analysis/TypeInferenceAnalysis.h
compilers/concrete-compiler/compiler/include/concretelang/Dialect/RT/TypeInference.h
compilers/concrete-compiler/compiler/include/concretelang/Transforms/TypeInferenceRewriter.h
compilers/concrete-compiler/compiler/lib/Dialect/RT/Analysis/LowerDataflowTasksToRT.cpp
compilers/concrete-compiler/compiler/lib/Dialect/TFHE/Transforms/TFHECircuitSolutionParametrization.cpp
compilers/concrete-compiler/compiler/lib/Support/CompilerEngine.cpp
compilers/concrete-compiler/compiler/lib/Support/Pipeline.cpp
compilers/concrete-compiler/compiler/tests/check_tests/TypeInference/inference-multifunc.mlir
compilers/concrete-compiler/compiler/tests/check_tests/TypeInference/inference.mlir
compilers/concrete-compiler/compiler/tests/end_to_end_tests/end_to_end_test.cc

Relies on the support of multiple functions from #823.

Type Inference: Add support for operations from the RT dialect

---

frontends/concrete-python/concrete/fhe/extensions/bits.py
frontends/concrete-python/concrete/fhe/mlir/context.py
frontends/concrete-python/tests/execution/test_bit_extraction.py

lsb and tlu calls were not minimized

fix(frontend-python): optimize extract bits

---

compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/client_support.py
compilers/concrete-compiler/compiler/lib/Bindings/Python/requirements_dev.txt

chore(compiler): update black dev dependency

---

frontends/concrete-python/concrete/fhe/mlir/context.py
frontends/concrete-python/examples/sha1/sha1.py
frontends/concrete-python/tests/execution/test_composition_compression.py

closes #https://github.com/zama-ai/concrete-internal/issues/727

fix(frontend): fixing pylint for SHA1 example

---

.github/workflows/concrete_python_release.yml
README.md

- Build a provenance file for all generated wheels on releases 
- Add a draft release
See https://slsa.dev/

feat(ci): add SLSA provenance

---

compilers/concrete-compiler/compiler/include/concretelang/Support/V0Parameters.h
compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/compilation_options.py
compilers/concrete-compiler/compiler/lib/Dialect/FHE/Analysis/ConcreteOptimizer.cpp
docs/guides/configure.md
frontends/concrete-python/concrete/fhe/compilation/configuration.py
frontends/concrete-python/concrete/fhe/compilation/server.py

Fixes zama-ai/concrete-internal#740

fix(frontend): add missing composition serialization

---

docs/get-started/installing.md

We missed to add GPU info in this part of the doc

doc(frontend-python): Additional information about GPU wheels install

---

compilers/concrete-compiler/compiler/include/concretelang/TestLib/TestProgram.h

gtest parallel distributes tests on different processes and not threads.

fix(compiler): fix racing the test directories on mac

---

.github/workflows/markdown_link_check.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17gpiTs3xHd2r1mYtkXjDVaO71QIRao%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=DhtzqE9)

chore(ci): Fix markdown link check

---

docs/tutorials/see-all-tutorials.md

- Upload 2 video tutorials during Q1
- Change the video links to Zama blog

Udpate tutorials in doc

---

compilers/concrete-compiler/compiler/tests/unit_tests/concretelang/Encodings/Encodings_unit_tests.cpp

Fixes a segfault in the unit tests that appeared when executed in debug mode on mac arm.

fix(compiler): segfault in tests

---

.github/workflows/concrete_python_release.yml

fix(ci): add leading 'v' in docker image tag

---

docs/SUMMARY.md
docs/core-features/non_linear_operations.md
docs/core-features/table_lookups.md
docs/dev/compatibility.md
docs/get-started/limitations.md
docs/get-started/terminology.md

docs(frontend): massive modifications in the documentation [part 1] 

---

docs/SUMMARY.md
docs/core-features/fhe_basics.md
docs/guides/deploy.md

refs #https://github.com/zama-ai/concrete-internal/issues/812
part 4

docs(frontend): massive modifications in the documentation [part 3]

---

compilers/concrete-compiler/compiler/lib/Transforms/ForLoopToParallel.cpp

The pattern converting `scf.for` operations to `scf.parallel` operations from `lib/Transforms/ForLoopToParallel.cpp` contains an assertion that ensures that the source operation does not have any iteration arguments in order to keep the conversion as simple as possible.
However, if the attribute `parallel` of the source operation is `false`, the operation is replaced with an identical clone and the conversion could be treated as a no-op.
This change modifies the pattern, such that it simply fails if `parallel` is `false`, making the check for the absence of iteration arguments unnecessary and avoiding unnecessary bailouts by the compiler.

fix(compiler): Convert scf.for to scf.parallel only if parallel attribute is true

---

README.md
frontends/concrete-python/examples/levenshtein_distance/README.md
frontends/concrete-python/examples/levenshtein_distance/levenshtein_distance.py

I'll merge that after @rudy-6-4 's fix for #956
I also need to redo benchmarks
closes #[819](https://github.com/zama-ai/concrete-internal/issues/819)

fix(frontend): fixing an issue in the string generation

---

docs/core-features/workarounds.md

docs(frontend-python): update workaround to refer to new features

---

frontends/concrete-python/concrete/fhe/compilation/server.py
frontends/concrete-python/tests/compilation/test_circuit.py

feat(frontend): support configuration overrides for Server.load when via_mlir is used

---

docs/guides/deploy.md
frontends/concrete-python/concrete/fhe/compilation/server.py
frontends/concrete-python/concrete/fhe/compilation/utils.py
frontends/concrete-python/tests/compilation/test_circuit.py

(closes https://github.com/zama-ai/concrete-internal/issues/828)

feat(frontend): accept clear arguments in server.run

---

frontends/concrete-python/Makefile
frontends/concrete-python/concrete/fhe/compilation/configuration.py
frontends/concrete-python/concrete/fhe/compilation/module.py
frontends/concrete-python/concrete/fhe/compilation/module_compiler.py
frontends/concrete-python/concrete/fhe/mlir/context.py
frontends/concrete-python/concrete/fhe/mlir/converter.py
frontends/concrete-python/concrete/fhe/representation/graph.py
frontends/concrete-python/concrete/fhe/tfhers/dtypes.py
frontends/concrete-python/concrete/fhe/tfhers/tracing.py
frontends/concrete-python/tests/compilation/test_circuit.py
frontends/concrete-python/tests/compilation/test_configuration.py
frontends/concrete-python/tests/compilation/test_modules.py
frontends/concrete-python/tests/execution/test_bit_extraction.py
frontends/concrete-python/tests/execution/test_min_max.py
frontends/concrete-python/tests/execution/test_others.py
frontends/concrete-python/tests/execution/test_tfhers.py
frontends/concrete-python/tests/representation/test_graph.py
frontends/concrete-python/tests/representation/test_node.py
frontends/concrete-python/tests/tracing/test_tracer.py

(closes https://github.com/zama-ai/concrete-internal/issues/825)

fix(frontend): get coverage back to 100 percent

---

.github/workflows/concrete_python_checks.yml
docs/explanations/dialects.md
docs/explanations/security.md
frontends/concrete-python/Makefile
frontends/concrete-python/requirements.dev.txt
frontends/concrete-python/scripts/checks/checks.sh
frontends/concrete-python/scripts/links/check_headers.py
frontends/concrete-python/scripts/links/check_internal_links.sh
frontends/concrete-python/scripts/links/local_link_check.py

I have seen too many broken links at release time, in Q2. So, adding scripts, to avoid broken links or bad links, highly inspired from equivalent checks on Concrete ML side.

chore(ci): adding local link checks

---

compilers/concrete-compiler/compiler/lib/Common/Transformers.cpp
frontends/concrete-python/tests/conftest.py
frontends/concrete-python/tests/execution/test_composition_compression.py

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX179M8cNw2cdj9mc734kfu3o4aVEH146RI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=bC33ae4)

Decompress ciphertext at decryption

---

docs/get-started/installing.md

followup of https://github.com/zama-ai/concrete/pull/1021

docs(frontend): fix commands to install wheels from zama package registry

---

docs/core-features/bit_extraction.md
docs/core-features/extensions.md
docs/core-features/fhe_basics.md
docs/core-features/non_linear_operations.md
docs/core-features/table_lookups.md
docs/core-features/workarounds.md
docs/get-started/quick_overview.md
docs/get-started/terminology.md

Hello, I've reviewed and edited the "Core features" part of the documentation to improve the readability. Please review to make sure my rewordings don't alter any technical meanings. Thank you!

Doc review and edits of "Core features" section

---

frontends/concrete-python/tests/execution/test_tfhers.py

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX15yrebV1kTtE5wM3IyrpELYHlhLMsp2k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=bF2aK5L)

test(frontend-python): Fixing tfhers compatibility tests

---

docs/guides/deploy.md
docs/guides/manage_keys.md

Hello! 
The main changes in this PR are in the "Deploy" : I transferred the deployment steps into numeric lists to improve the readability (making the page more "scannable")
Please have a look to see if you want to add/delete any content on this structure.
Thanks!

Doc edits: Manage keys and Deploy

---

docs/dev/compatibility.md
docs/optimization/improve-parallelism/dataflow.md
docs/optimization/improve-parallelism/self.md
docs/optimization/improve-parallelism/tensorization.md
docs/optimization/optimize-cryptographic-parameters/composition.md
docs/optimization/optimize-cryptographic-parameters/p-error.md
docs/optimization/optimize-cryptographic-parameters/self.md
docs/optimization/self.md

Hello,
This PR contains several mds but the edits are very minor. 
Thanks!

Doc edits: Optimization

---

docs/compilation/direct_circuits.md
docs/core-features/bitwise.md
docs/core-features/comparisons.md
docs/core-features/floating_points.md
docs/core-features/minmax.md
docs/core-features/rounding.md
docs/core-features/table_lookups_advanced.md
docs/core-features/tagging.md
docs/core-features/truncating.md
docs/dev/compilation/compiler_workflow.md
docs/explanations/fusing.md
docs/explanations/security.md

closes #https://github.com/zama-ai/concrete-internal/issues/837

docs(frontend): adding small intros

---

frontends/concrete-python/concrete/fhe/compilation/compiler.py
frontends/concrete-python/concrete/fhe/compilation/decorators.py
frontends/concrete-python/tests/compilation/test_compiler.py
frontends/concrete-python/tests/compilation/test_decorators.py

(closes https://github.com/zama-ai/concrete-internal/issues/845)

feat(frontend): provide an API to reset the compiler state

---

.github/workflows/concrete_python_test_macos.yml
.github/workflows/concrete_python_tests_linux.yml
frontends/concrete-python/Makefile
frontends/concrete-python/examples/floating_point/floating_point.ipynb
frontends/concrete-python/examples/levenshtein_distance/IBAN_name_check.ipynb
frontends/concrete-python/examples/sha256/sha256.ipynb
frontends/concrete-python/requirements.dev.txt
frontends/concrete-python/scripts/jupyter/jupyter.sh

- Adding a new test `make jupyter`, to run and test the notebooks
- Fixing all the broken notebooks
close #https://github.com/zama-ai/concrete-internal/issues/855

Adding notebook tests 855

---

docs/guides/deploy.md
docs/guides/manage_keys.md

minor doc changes which followed https://github.com/zama-ai/concrete/pull/1019 merge.
closes https://github.com/zama-ai/concrete-internal/issues/#840

docs(frontend-python): improving the doc

---

frontends/concrete-python/examples/levenshtein_distance/README.md
frontends/concrete-python/examples/prime-match/README.md

partially close #854 (sha1 still need a fix)

chore(frontend): bench examples on hpc7a

---

compilers/concrete-compiler/compiler/lib/Dialect/FHE/Analysis/MANP.cpp

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX14I3eK6jgD3hs0RhsDtfFfwILXui2Mus%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MFJGMOq)
We will later add gcc-13 ti the CI

fix(compiler): Fixing warnings spotted by gcc-13

---

.github/workflows/concrete_python_release.yml
docs/compilation/common_errors.md
docs/get-started/installing.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19udF3HCqsCLfWeCH1eBKEXNSEUl3t74%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=lgpYH_k)

Support python3 12

---

.github/workflows/concrete_python_release_cpu.yml

fix(ci): copy examples in test env

---

.github/workflows/concrete_python_release_cpu.yml

fix(ci): use relative path to script

---

.github/workflows/concrete_python_release_cpu.yml

https://github.com/zama-ai/concrete/actions/runs/11926018502/job/33240352437

fix(ci): export cargo env

---

.github/workflows/concrete_python_release_gpu.yml

fix(ci): setup cargo in GPU release tests

---

frontends/concrete-python/concrete/__init__.py

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19B9TGRUNRgmxYYGztm6KcLjpuAa8s%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=EFYJACz)

fix(frontend-python): Ignore pkg_resources warning

---

.github/workflows/action_compliance.yaml
.github/workflows/concrete_compiler_benchmark.yml
.github/workflows/concrete_compiler_publish_docker_images.yml
.github/workflows/concrete_ml_test.yml
.github/workflows/concrete_optimizer.yml
.github/workflows/concrete_python_release_cpu.yml
.github/workflows/concrete_python_release_gpu.yml
.github/workflows/concrete_python_tests_linux.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18oLyvdKMi8afSn705AlAeIQxymkygcyXo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QB4DiKk)

Updates by dependabot

---

frontends/concrete-python/Makefile
frontends/concrete-python/pytest.ini
frontends/concrete-python/tests/compilation/test_circuit.py
frontends/concrete-python/tests/compilation/test_modules.py
frontends/concrete-python/tests/execution/test_add.py
frontends/concrete-python/tests/execution/test_direct_table_lookup.py
frontends/concrete-python/tests/execution/test_mul.py

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX15swP38u0pQA6Oq3a7jMN3GzuZ3ovh0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QYxxC0L)

chore(frontend-python): Run minimal tests on macos and gpu

---

.github/workflows/concrete_python_test_macos.yml
frontends/concrete-python/Makefile

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18tXhXDRpMkOc0OKNKxxpl1uOHcCUrj7I%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=bqlLU0i)

chore(ci): Fix macos notebook test

---

.github/workflows/concrete_ml_test.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1OsO04fkqQH4WslLrWkcKiJTS1KAXG3U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=My29K8O)

Update poetry of concrete-ml test

---

compilers/concrete-compiler/compiler/include/concretelang/Dialect/RT/Analysis/Autopar.h
compilers/concrete-compiler/compiler/include/concretelang/Dialect/RT/Analysis/Autopar.td
compilers/concrete-compiler/compiler/include/concretelang/Runtime/runtime_api.h
compilers/concrete-compiler/compiler/lib/Dialect/RT/Analysis/BufferizeDataflowTaskOps.cpp
compilers/concrete-compiler/compiler/lib/Dialect/RT/Analysis/BuildDataflowTaskGraph.cpp
compilers/concrete-compiler/compiler/lib/Dialect/RT/Analysis/LowerDataflowTasksToRT.cpp
compilers/concrete-compiler/compiler/lib/Runtime/DFRuntime.cpp
compilers/concrete-compiler/compiler/lib/Support/Pipeline.cpp
compilers/concrete-compiler/compiler/tests/check_tests/Transforms/StartStop/auto_parallelize.mlir
compilers/concrete-compiler/compiler/tests/check_tests/Transforms/StartStop/dfr_parallelize_no_loop.mlir

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18eed0cL1FLdIJiha2eTcxnJQz85UQFak%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=DGtrz8d)

fix(compiler/runtime): Setup omp on the DFR runtime if needed

---

.github/workflows/concrete_python_release.yml
frontends/concrete-python/Makefile

Fixes https://github.com/zama-ai/concrete/actions/runs/14850881467/job/41696609345#step:8:654

fix(ci): specify concrete-keygen directory
