zama-ai/concrete

- concrete-core/src/crypto/cross/mod.rs
> fix: bootstrap do not require a mutable bootstrap key

- concrete-core/Cargo.toml
- concrete-core/src/math/fft/mod.rs
- concrete-core/src/math/fft/transform.rs
The concrete-core uses AlignedVec from fftw, but does not re-export it,
forcing users to depend on fftw to use it, so re-export it.
Additionally, update to 0.7 to have AlignedVec be Send + Sync.
> feat: update fftw to 0.7, re-export AlignedVec

- .github/templates/pull_request_template.md
When creating a pull request this template should be used by github to pre-fill the PR description. I followed this page:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template
> Create pull request template

- concrete-core/benches/bootstrap.rs
Benchmarks were not fixed after the new bootstrap api was added. This fixes it.
Resolves #54
> fix(bench): fixes bootstrap api in benchmarks.

- .github/workflows/aws_tests.yml
- .github/workflows/build.yml
- .github/workflows/build_benches.yml
The dependency on the system installation of libfftw was removed from
the CI in commit 6743dce, because the dependency on the system fftw
library was removed from `concrete-core=0.1.10`. It was a mistake, as
the `concrete` crate still depends on `concrete-core=0.1.9`, which
itself depends on `fftw-sys`, with the `system` features, which requires
libfftw to be installed.
This commit restore the installation of the system fftw in the CI, to
solve this issue.
> fix(ci): restore fftw system dependency.

- concrete-core/src/crypto/glwe/ciphertext.rs
- concrete-core/src/crypto/lwe/ciphertext.rs
- concrete-core/src/crypto/secret/glwe.rs
- concrete-core/src/math/tensor/tensor.rs
This commit brings lwe sample extraction to the public API of `concrete-core`. The methods  `GlweCiphertext::fill_lwe_with_sample_extraction` and `LweCiphertext::fill_with_glwe_sample_extraction` make it possible to extract any coefficient of a `GlweCiphertext`, into a properly sized `LweCiphertext`. The elements of the mask are rearranged in such a way that reinterpreting the `GlweSecretKey` into a `LweSecretKey` via the `GlweSecretKey::into_lwe_secret_key` method (without making any change in the order of the underlying array of elements), allows to decrypt the newly created `LweCiphertext`.
This commit also adds three new methods to the `Tensor` type, the `reverse`, `rotate_left`, and …
> feat(concrete-core): add lwe sample extraction to the public API.

- concrete-core/src/math/fft/transform.rs
cast bsk to signed integers before forward fft to reduce the fft noise as described in zama-ai/concrete_internal#132
> Fix: cast bootstrap key to signed integers before forward FFT

- .github/workflows/aws_tests.yml
- concrete-core/src/crypto/bootstrap/fourier/mod.rs
- concrete-core/src/crypto/bootstrap/fourier/tests.rs
- concrete-core/src/crypto/lwe/keyswitch.rs
- concrete-core/src/crypto/secret/lwe.rs
- concrete-core/src/lib.rs
- concrete-core/src/math/fft/transform.rs
- concrete-csprng/src/counter/mod.rs
- concrete/src/encoder/tests.rs
- concrete/src/lib.rs
- concrete/src/vector_lwe/mod.rs
New lints were added to clippy, and that broke the CI. This commit fixes it.
> fix(workspace): fix new clippy lints

- README.md
This reworks the Installations section of the readme by:
- Removing instructions to install pre-built `fftw` libs
as `concrete-fftw` builds it from source pre-build libs
are not needed anymore.
- Add instructions for the 3 major OSes: Linux, macOS, Windows
- Add instructions for Apple Silicon users
> chore(ecosystem): Rework Readme.md's Installation section

- concrete-core/src/backends/core/private/math/fft/transform.rs
- concrete-csprng/src/counter/test.rs
- use `flat_map` as suggested by clippy
- don't do a late initialization of a viariable
~~* [ ] Tests for the changes have been added (for bug fixes / features)~~'
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] The draft release description has been updated~~
> fix(csprng,core): address 2 clippy lints

- concrete-npe/src/operators.rs
Typo in the noise formula of 'estimate_external_product_noise_with_binary_ggsw' in concrete-npe.
> fix(concrete_npe): fix typo in formula

- .github/workflows/aws_tests.yml
- concrete-core/src/backends/core/implementation/engines/lwe_ciphertext_vector_discarding_affine_transformation.rs
- concrete-core/src/backends/core/private/math/fft/transform.rs
- concrete-core/src/lib.rs
- concrete-core/src/specification/engines/lwe_ciphertext_vector_discarding_affine_transformation.rs
- concrete-core/src/specification/engines/mod.rs
In 7877ea8295dd8775010a405590ae431d92d35ff4 we removed the deny cfg for
broken intra doc links, which lead to a broken CI. This commit resolves
that.
> fix(ci): fixes broken doc verification

- Cargo.toml
The commit 7877ea8295dd8775010a405590ae431d92d35ff4
removed the `lto = "fat"` from the workspace
`Cargo.toml`. Without this, the `concrete-boolean`
benchmarks give much slower results.
Example:
AND gate __without__ lto=fat: ~32ms
AND gate __with__ lto=fat: ~10ms
This commit re-enables fat lto for the bench profile.
~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] The draft release description has been updated~~
> chore(ecosystem): enable link time optimizations in benches

- concrete-npe/src/operators.rs
The base log value was wrong in the PBS noise formula.
> fix(concrete_npe): fix base log in the pbs noise

- concrete-boolean/src/server_key/tests.rs
- concrete-core/Cargo.toml
- concrete-npe/Cargo.toml
zama-ai/concrete_internal#280
The current (unpublished) version of `concrete-npe` is `0.1.2`, but it contains many breaking changes. This commit changes that to release it as a new major version, i.e. `0.2.0`.
> chore(concrete_npe): bumps major version

- concrete-core/docs/api/backends.md
This small PR just fixes the links to the rust documentation in `concrete-core`'s user documentation.
> Fix links to rust doc in concrete-core's user documentation

- concrete-csprng/src/aesni.rs
zama-ai/concrete_internal#304
A newly added clippy lint prevented the ci to pass. This commit fixes
that.
> fix(concrete_csprng): fix the `transmute_undefined_repr` lint

- concrete-core/src/backends/core/private/crypto/secret/lwe.rs
zama-ai/concrete_internal#113
The private `decrypt_lwe` entry point was adding the result of the decryption to the `output` argument instead of overriding it. This commit fixes that.
> fix(concrete_core): fixes the semantics of lwe decryption

- concrete-npe/src/operators.rs
- concrete-npe/src/tools.rs
Some modular_variance values are used as normal scale variance
> fix(concrete-npe): weighted sum returns invalid variance scale

- concrete-core-fixture/src/fixture/cleartext_creation.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
zama-ai/concrete_internal#325
The fixture crate re-generated all the inputs for each test that was
performed. For performance reasons though, we needed to be able to
reuse some of those inputs across executions (for example, perform
all the tests with one or several BSK, not regenerating the BSK for
each sample).
This commit introduces a different structure for the fixture, which
allows that.
> feat(concrete-core): rework fixtures to increase performance with reuse

- concrete-core-fixture/src/fixture/cleartext_creation.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `LweCiphertextDiscardingEncryptionEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add lwe ciphertext discarding encryption fixture

- concrete-core/src/backends/core/implementation/engines/lwe_ciphertext_discarding_bootstrap.rs
When the doc test for the bootstrap was written, the trivial encryption of a GLWE was not exposed in the public API. Now that it is, it seems better to use it to encrypt the LUT in the doc test.
> Trivially encrypt the lut in the bootstrap doc test

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_decryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
https://github.com/zama-ai/concrete_internal/issues/224
This commit adds a fixture for the `LweCiphertextVectorDecryptionEngine`, and adds a test using it to `concrete-core-test`.
#150 
> feat(concrete_core): add lwe ciphertext vector decryption fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_affine_transformation.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
- concrete-core/src/backends/core/private/crypto/lwe/tests.rs
This commit adds a fixture for the `LweCiphertextVectorDiscardingAffineTransformationEngine`, and adds a test using it to `concrete-core-test`.
#153 
>  feat(concrete_core): add lwe ciphertext vector discarding affine transformation fixture

- concrete-core-fixture/src/fixture/cleartext_retrieval.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `CleartextRetrieval`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add cleartext retrieval fixture

- concrete-core/src/backends/core/implementation/engines/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
- concrete-core/src/backends/core/implementation/engines/glwe_ciphertext_ggsw_ciphertext_external_product.rs
- concrete-core/src/backends/core/implementation/engines/lwe_ciphertext_discarding_bootstrap.rs
- concrete-core/src/backends/core/implementation/engines/mod.rs
- concrete-core/src/backends/core/private/math/fft/mod.rs
- concrete-core/src/backends/core/private/math/fft/plan.rs
- concrete-core/src/backends/core/private/math/fft/tests.rs
- concrete-core/src/backends/core/private/math/fft/transform.rs
There is currently no error in the core backend for unsupported polynomial sizes. This PR adds it.
> chore(core): add an error for unsupported polynomial size in core engine

- concrete-core-fixture/src/fixture/cleartext_discarding_retrieval.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `CleartextDiscardingRetrieval`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add cleartext discarding retrieval fixture

- concrete-core-fixture/src/fixture/cleartext_vector_creation.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `CleartextVectorCreationEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add cleartext vector creation fixture

- concrete-core-fixture/src/fixture/cleartext_vector_discarding_retrieval.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `CleartextDiscardingRetrieval`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add cleartext vector discarding retrieval fixture

- concrete-core-fixture/src/fixture/cleartext_vector_retrieval.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `CleartextVectorCreationEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add cleartext vector retrieval fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_decryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `GlweCiphertextDecryptionEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add glwe ciphertext decryption fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_decryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
Add a fixture and a test for the core backend implementation of the lwe_ciphertext_decryption engine
> Add fixture & test for lwe_ciphertext_decryption

- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/fixture/plaintext_discarding_retrieval.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `PlaintextDiscardingRetrievalEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add plaintext discarding retrieval fixture

- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/fixture/plaintext_retrieval.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `PlaintextRetrievalEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add plaintext retrieval fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_decryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `GlweCiphertextDiscardingDecryptionEngine`, and adds a test using it to `concrete-core-test`.
> feat(concrete_core): add glwe ciphertext discarding decryption fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_addition.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextDiscardingAdditionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext discarding addition fixture

- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/fixture/plaintext_vector_discarding_retrieval.rs
- concrete-core-test/src/core.rs
[zama-ai/concrete_internal/issues#224](https://github.com/zama-ai/concrete_internal/issues/224)
This PR adds a fixture for the `PlaintextVectorDiscardingRetrievalEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add plaintext vector discarding retrieval fixture

- concrete-core-fixture/src/fixture/cleartext_vector_creation.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_trivial_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_trivial_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_trivial_encryption.rs
zama-ai/concrete_internal#366
When merging the fixtures, we added parameters with `PolynomialSize(1)` which is forbidden for glwe in concrete-core.
> fix(core): remove forbidden polynomial size of one

- concrete-core/src/backends/core/implementation/engines/glwe_ciphertext_vector_trivial_decryption.rs
The u32 doc test was failing because we applied a shift of 50 bits in the encoding.
> fix(core): fix encoding in the doc test of glwe_ciphertext_vector_trivial_decryption

- concrete-core-fixture/src/fixture/lwe_ciphertext_fusing_addition.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextFusingAdditionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext fusing addition fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_zero_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
Add the fixture & test for the LWE ciphertext zero encryption.
> test(core): add a fixture for the lwe ciphertext zero encryption

- concrete-core-fixture/src/fixture/lwe_ciphertext_fusing_negation.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextFusingNegationEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext fusing negation fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_subtraction.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextDiscardingSubtractionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext discarding subtraction fixture

- .github/workflows/aws_tests.yml
To speed up AWS test runs a CPU with AES, RDSEED and SSE2 instructions
is mandatory. AWS EC2 m5n instance type fulfill this need.
This also uses a new AWS image with build dependencies already installed.
> chore(ci): change instance type to get extended CPU instructions

- concrete-core-fixture/src/fixture/lwe_ciphertext_fusing_subtraction.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextFusingSubtractionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext fusing subtraction fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_decryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the LweCiphertextDiscardingDecryptionEngine, and adds a test using it to concrete-core-test.
> test(core): add lwe ciphertext discarding decryption fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_plaintext_discarding_addition.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextPlaintextDiscardingAdditionEngine`, and adds a test using it to concrete-core-test.
> test(core): add lwe ciphertext plaintext discarding addition fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture & test for lwe_ciphertext_vector_encryption
> test(core): add a fixture & test for lwe_ciphertext_vector_encryption

- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/fixture/plaintext_vector_retrieval.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `PlaintextVectorRetrievalEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add plaintext vector retrieval fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_plaintext_fusing_addition.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextPlaintextFusingAdditionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext plaintext fusing addition fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_plaintext_discarding_subtraction.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextPlaintextDiscardingSubtractionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext plaintext discarding subtraction fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
Add a test and fixture for lwe ciphertext vector discarding encryption
> test(core): add fixture & test for lwe ciphertext vector discarding encryption

- concrete-core-fixture/src/fixture/lwe_ciphertext_plaintext_fusing_subtraction.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This PR adds a fixture for the `LweCiphertextPlaintextFusingSubtractionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext plaintext fusing subtraction fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_trivial_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/generation/prototyping/glwe_ciphertext.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `GlweCiphertextTrivialEncryptionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add glwe ciphertext trivial encryption fixture

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_extraction.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/generation/prototyping/glwe_secret_key.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `LweCiphertextDiscardingExtractionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add lwe ciphertext discarding extraction fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `GlweCiphertextVectorEncryptionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add glwe ciphertext vector encryption fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_zero_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
This commit adds a fixture for the `GlweCiphertextZeroEncryptionEngine`, and adds a test using it to `concrete-core-test`.
> test(core): add glwe ciphertext zero encryption fixture

- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_zero_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-test/src/core.rs
Add fixture and test for GLWE ciphertext vector zero encryption.
> test(core): add fixture and test for glwe vector zero encrypt

- .github/workflows/aws_tests.yml
- .github/workflows/check_commit.yml
- .github/workflows/docs_boolean.yml
- .github/workflows/docs_core.yml
- concrete-boolean/docs/versions.json
- concrete-core/docs/versions.json
- Trigger CI action on default branch main instead of master
- Build current doc version under `main` name instead of `master`
> chore(ci): rename default branch to main

- concrete-core/src/backends/core/implementation/engines/mod.rs
- concrete-core/src/specification/engines/ggsw_ciphertext_scalar_trivial_encryption.rs
- concrete-core/src/specification/engines/glwe_ciphertext_trivial_decryption.rs
- concrete-core/src/specification/engines/glwe_ciphertext_trivial_encryption.rs
- concrete-core/src/specification/engines/glwe_ciphertext_vector_trivial_decryption.rs
- concrete-core/src/specification/engines/glwe_ciphertext_vector_trivial_encryption.rs
- concrete-core/src/specification/engines/lwe_ciphertext_trivial_decryption.rs
- concrete-core/src/specification/engines/lwe_ciphertext_trivial_encryption.rs
- concrete-core/src/specification/engines/lwe_ciphertext_vector_trivial_decryption.rs
- concrete-core/src/specification/engines/lwe_ciphertext_vector_trivial_encryption.rs
zama-ai/concrete_internal#298
zama-ai/concrete_internal#302
- add an explanation about Fourier buffers
- add small explanation about why trivial encryptions can be useful
> docs(core): small fixes in the doc

- concrete-core-fixture/src/raw/statistical_test.rs
There was a rounding in the computation of the standard deviation which made some tests fail regularly. It is removed and replaced by the addition of some margin in the comparison of standard deviations.
> test(core): remove the rounding from the variance calculation in the test

- concrete-core/Cargo.toml
- concrete-core/docs/versions.json
- concrete-npe/Cargo.toml
This PR increases version numbers for concrete-core and concrete-npe (concrete-commons' version was already increased when a breaking change was introduced earlier in the quarter, due to the serde serialization that became optional).
Beware that I based this PR on top of the two PRs that are waiting to be merged before the release, so that I can run the CI with the full release sources: #243 and #172 
> chore(core_npe): bump versions

- concrete-core-fixture/src/fixture/glwe_ciphertext_ggsw_ciphertext_external_product.rs
For some application, one might want to be able to select a fixed
value for GGSW in the repetition prototypes creation or get it by
randomly picking a value in a range.
> feat(fixture): Make GGSW value selectable

- concrete-core/src/backends/core/private/crypto/bootstrap/fourier/mod.rs
This is just a minor refactoring to use the existing fill_with_forward_fourier of the GGSW in the Fourier bootstrap key.
> chore(core): refactor fill_with_forward_fourier

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_conversion.rs
- concrete-core/docs/dev/benchmarking_backends.md
- concrete-core/docs/dev/testing_backends.md
This PR fixes the LWE ciphertext vector conversion fixture and updates the two tutorials for testing & benchmarking backends.
> fix(fixture): fix the lwe vector conversion fixture

- concrete-boolean/Cargo.toml
- concrete-boolean/src/client_key/mod.rs
- concrete-boolean/src/lib.rs
- concrete-boolean/src/server_key/mod.rs
This PR updates the `backend_optalysys` version of `concrete-boolean` to account for the new structure of `concrete-core`. The two main changes are: 
* References to `CoreEngine` are replaced by `DefaultEngine`.
* The crate `rand` becomes a dependency (as opposed to a dev-dependency) as it is used to generate the seed for the default backend. 
To avoid introducing an additional dependency, the seed for the `DefaultEngine` is generated using `rand::thread_rng`. This RNG is supposed to be cryptographically secure, although I am not familiar enough with it to know for sure whether it is secure enough to be used here.
> Update the `optalysys_backend` version of concrete-boolean

- concrete/CHANGELOG.md
- concrete/Cargo.toml
- concrete/src/config.rs
- concrete/src/integers/keys.rs
- concrete/src/keycache.rs
- concrete/src/lib.rs
- concrete/src/prelude.rs
- concrete/src/shortints/static/server_key.rs
- concrete/src/shortints/static/types.rs
- concrete/src/traits.rs
- concrete/tests/test_shortints.rs
This PR introduces:
-  `FheOrd` and `FheEq` traits to have scalar and chipertexts comparisons using the same methods
names (`eq`, `lt`, ...)
- `std::iter::{Sum, Product}`  for shortints
- Trivial encryptions for shortints
- A KeyCacher struct
I don't think it contains breaking changes
> FheOrd, FheEq

- concrete/docs/README.md
keep the code names client/server key but introduce their sensitivity and alternative name (evaluation key)
> docs: clarify keys usage in introduction

- ci/slab.toml
In the next Slab CI bot release, the inner workings of the server change a bit. In order to have more flexibility on command declaration and EC2 profile definitions for each repositories, the configuration belongs now to each repo.
Each time a command is run from a PR, the file `ci/slab.toml` will be fetched and read from the branch the PR refers to. A great aspect of this behavior is the ability to add a new command/profile in your PR to test your code in other conditions. Another one is to avoid having hardcoded profiles structs and commands in Slab, and thus remove the need to make a release or reboot Slab in case of global configuration changes.
> ci: add remote configuration for slab ci bot

- .github/workflows/cargo_build.yml
- .github/workflows/cargo_test_boolean.yml
- .github/workflows/lint.yml
- .github/workflows/scheduled_lint.yml
- concrete-boolean/Cargo.toml
- concrete-boolean/benches/bench.rs
- concrete-boolean/src/client_key/mod.rs
- concrete-boolean/src/engine/bootstrapping/cpu.rs
- concrete-boolean/src/engine/bootstrapping/cuda.rs
- concrete-boolean/src/engine/bootstrapping/mod.rs
- concrete-boolean/src/engine/mod.rs
- concrete-boolean/src/lib.rs
- concrete-boolean/src/prelude.rs
- concrete-boolean/src/server_key/mod.rs
- concrete-boolean/src/server_key/tests.rs
fixes zama-ai/concrete_internal#537
This adds a `cuda` feature to the concrete-boolean crate.
When this feature is enabled, the bootstrap and keyswitch steps are done one the
gpu using concrete-core cuda backend.
BREAKING_CHANGE: ServerKey representation changed, thus previously serialized keys are not compatible.
> Concrete boolean cuda

- concrete-boolean/Cargo.toml
- concrete-integer/Cargo.toml
Some features were missing and could lead to compile errors depending on the target_arch
> fix(aarch64): activate missing features for aarch64 targets

- concrete-boolean/Cargo.toml
- concrete-integer/Cargo.toml
- concrete-shortint/Cargo.toml
This will also imply resolver=2 which our crates needs to be able to target different archs.
> fix(crates): bump our editions to 2021

- backends/concrete-cuda/implementation/include/vertical_packing.h
- backends/concrete-cuda/implementation/src/bit_extraction.cuh
- backends/concrete-cuda/implementation/src/vertical_packing.cu
- backends/concrete-cuda/implementation/src/vertical_packing.cuh
- backends/concrete-cuda/implementation/src/wop_bootstrap.cu
- backends/concrete-cuda/implementation/src/wop_bootstrap.cuh
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_cmux_tree.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/include/setup_and_teardown.h
- backends/concrete-cuda/implementation/test_and_benchmark/setup_and_teardown.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/test/test_cmux_tree.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/test/test_wop_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp
**Solves**: https://github.com/zama-ai/concrete-open-source/issues/95
**Description**: This PR adds support to the case when `number_of_inputs * number_of_extracted_bits < log2(N)`. We follow the technique implemented in concrete-cpu.
> feat(backend-gpu): refactor the Wop-PBS implementation to support a wider set of parameters

- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/README.md
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bit_extraction.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_circuit_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_cmux_tree.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_keyswitch.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_linear_algebra.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_wop_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/include/utils.h
- backends/concrete-cuda/implementation/test_and_benchmark/setup_and_teardown.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp
- ci/benchmark_parser.py
- ci/ec2_products_cost.json
The new column calculates
```
number_of_iterations / (cost_per_second * total_execution_time_in_seconds)
```
Google Benchmarks appends "/s" to the result when reported to the standard output, which is wrong. However, the JSON output is not affected by that issue.
> feat(backend-gpu): add a new column to the benchmark tool to automatically compute the throughput per dollar for an AWS instance

- backends/concrete-cuda/implementation/include/bootstrap.h
- backends/concrete-cuda/implementation/include/circuit_bootstrap.h
- backends/concrete-cuda/implementation/src/bit_extraction.cuh
- backends/concrete-cuda/implementation/src/boolean_gates.cu
- backends/concrete-cuda/implementation/src/bootstrap_amortized.cuh
- backends/concrete-cuda/implementation/src/bootstrap_fast_low_latency.cuh
- backends/concrete-cuda/implementation/src/bootstrap_low_latency.cu
- backends/concrete-cuda/implementation/src/bootstrap_low_latency.cuh
- backends/concrete-cuda/implementation/src/circuit_bootstrap.cu
- backends/concrete-cuda/implementation/src/circuit_bootstrap.cuh
- backends/concrete-cuda/implementation/src/polynomial/polynomial_math.cuh
- backends/concrete-cuda/implementation/src/wop_bootstrap.cu
- backends/concrete-cuda/implementation/src/wop_bootstrap.cuh
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/setup_and_teardown.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/test/test_bootstrap.cpp
**Solves:** https://github.com/zama-ai/concrete-core-internal/issues/246
This PR rewrites the low latency kernel so we don't use cooperative groups anymore. The new solution splits the algorithm in two different kernels that are launched a total of  `2 * lwe_dimension` times. 
The performance impact ~seems to be~ is not negligible, ~since each kernel is much lighter~ so I keep both implementations and select each one of them according to the parameter set. We no longer have so strong constraints on the parameter sets used, including the number of inputs.
> refactor(backend-gpu): drop dependency on cooperative groups

- compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHE/IR/FHEOps.td
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHELinalg/IR/FHELinalgOps.td
- compilers/concrete-compiler/compiler/lib/Dialect/FHE/IR/FHEOps.cpp
- compilers/concrete-compiler/compiler/lib/Dialect/FHELinalg/IR/FHELinalgOps.cpp
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHE/folding.mlir
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHE/round.invalid.mlir
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/folding.mlir
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/round.invalid.mlir
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19TNcwOtYaBX40mZUUzRgTqIFZMcDpM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vI9ggwz)
> fix(compiler/fhe): Allows noop FHE.round operators and fold it

- backends/concrete-cuda/implementation/src/bootstrap_amortized.cu
- backends/concrete-cuda/implementation/src/bootstrap_low_latency.cu
- backends/concrete-cuda/implementation/src/crypto/bootstrapping_key.cuh
- backends/concrete-cuda/implementation/src/polynomial/parameters.cuh
For the new low lat bootstrap, try out reducing the opt value from N = 2048 up to N = 16384 to see the effect on performance.
Benchmark results [here](https://zama.grafana.net/d/V_hSFNYVk/concrete-cuda-operation-performance-evolution-multi-branches?orgId=1&var-hardware=p3.2xlarge&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F656%2F2%2F512%2F8%2F2%2F1&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F656%2F2%2F512%2F8%2F2%2F1000&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F678%2F5%2F256%2F15%2F1%2F1&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F678%2F5%2F256%2F15%2F1%2F1000&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F684%2F3%2F512%2F18%2F1%2F1&var-test=Bootstrap_u64%2FConcreteCuda_LowLatencyPBS%2F684%2F3%2F512%2F18%2F1%2F1000&var-test=Bootstrap_u64%2FC …
> fix(backend-gpu): decrease opt values for N >= 2048

- backends/concrete-cuda/implementation/src/bootstrap_low_latency.cu
- backends/concrete-cuda/implementation/src/crypto/bootstrapping_key.cuh
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/CMakeLists.txt
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_bootstrap.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/include/utils.h
- backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp
Remove amortized PBS bench & bench with copy as well, it is deprecated
> bench(backend-gpu): multi-gpu support in bootstrap benchmark

- compilers/concrete-compiler/compiler/lib/Conversion/Utils/Dialects/SCF.cpp
The reinstantianting rewrite pattern for `scf.for` operations, `TypeConvertingReinstantiationPattern<scf::ForOp, false>`, calls `mlir::ConversionPatternRewriter::replaceOpWithNewOp()` before moving the operations of the original loop to the newly created loop. Since `replaceOpWithNewOp()` indirectly marks all operations of the old loop as ignored for dialect conversion, the dialect converter never descends recursively into the newly created loop.
This causes operations that are illegal to be preserved, which results in illegal IR after dialect conversion.
This commit splits the replacement into three steps:
1. Creation of the new loop via mlir::ConversionPatternRewriter::create()`
2. Moving operations from the old loop to the newly created one
3. Replacement of the original loop with the …
> fix(compiler): Move operations in scf.for reinstantiation pattern beore replacement

- docker/Dockerfile.concrete-python
the concrete-python docker image didn't have the `ld` binary, which is required during compilation
> fix(compiler/frontend): provide `ld` in the docker image

- compilers/concrete-compiler/compiler/lib/Support/ClientParametersGeneration.cpp
- compilers/concrete-compiler/compiler/tests/end_to_end_fixture/tests_cpu/bug_report_small.yaml
client parameter generation was removing last dimension of a tensor when using CRT including plaintext ones, while it should only be done for encrypted ones.
When compiling an example that uses CRT
```cpp
func.func @main(%arg0: tensor<4x4x!FHE.eint<13>>, %arg1: tensor<4x4xi14>) -> tensor<4x4x!FHE.eint<13>> {
%0 = "FHELinalg.matmul_eint_int"(%arg0, %arg1) : (tensor<4x4x!FHE.eint<13>>, tensor<4x4xi14>) -> tensor<4x4x!FHE.eint<13>>
%1 = "FHELinalg.matmul_eint_int"(%0, %arg1) : (tensor<4x4x!FHE.eint<13>>, tensor<4x4xi14>) -> tensor<4x4x!FHE.eint<13>>
%2 = "FHELinalg.matmul_eint_int"(%1, %arg1) : (tensor<4x4x!FHE.eint<13>>, tensor<4x4xi14>) -> tensor<4x4x!FHE.eint<13>>
%3 = "FHELinalg.matmul_eint_int"(%2, %arg1) : (tensor<4x4x!FHE.eint<13>>, tensor<4x4xi14>) -> tensor<4x4x!FHE.eint<13>>
return …
```
> fix(compiler): fix plaintext tensor shape when using crt

- backends/concrete-cuda/implementation/include/device.h
- backends/concrete-cuda/implementation/src/bootstrap_fast_low_latency.cuh
- backends/concrete-cuda/implementation/src/device.cu
Solves [#533](https://github.com/orgs/zama-ai/projects/21/views/2?pane=issue&itemId=27417534).
We were checking for cooperative groups support on the CI and if the grid size were supported in runtime, but we were not checking for cooperative groups support in runtime. Now we are.
> feat(backend-gpu): introduce a function to check for cooperative groups support

- backends/concrete-cuda/implementation/include/ciphertext.h
- backends/concrete-cuda/implementation/src/ciphertext.cu
- backends/concrete-cuda/implementation/src/crypto/ciphertext.cuh
- backends/concrete-cuda/rust_api/Cargo.toml
- backends/concrete-cuda/rust_api/LICENSE
- backends/concrete-cuda/rust_api/build.rs
- backends/concrete-cuda/rust_api/get_os_name.sh
- backends/concrete-cuda/rust_api/src/cuda_bind.rs
- backends/concrete-cuda/rust_api/src/lib.rs
Solves [#539](https://github.com/zama-ai/concrete-core-internal/issues/539)
This PR recovers the rust API so tfhe-rs can use concrete-cuda. It also adds support to the copy of LWE ciphertexts to/from GPU and CPU.
> feat(backend-gpu): expose a rust API for concrete-cuda

- .gitignore
- ci/scripts/test_cml.sh
- clone CML
- replace CP by a chosen one (either a X.Y.Z or the last weekly or the CP which corresponds to the current Concrete branch)
- install
- launch their test
refs [#430](https://github.com/zama-ai/concrete-internal/pull/430)
--
Typical usage:
`./test_cml.sh --cp_version 2.0.0`
Launch tests with CP 2.0.0
`./test_cml.sh --last_nightly_cp_version`
Launch tests with the last nightly
`./test_cml.sh --last_cp_version --ml_branch 3831-integrate-latest-changes-of-concrete-python`
Test with a given branch of CML
`./test_cml.sh -usage`
See all options
> test(frontend): add a script to launch tests with CML

- compilers/concrete-compiler/compiler/lib/Dialect/RT/IR/RTTypes.cpp
Printing the mnenomic in the custom printers for RT types leads to a repetition, since the mnenomic is already printed by the infrastructure invoking the custom printer (e.g., instead of RT.future<...>, the printed type is `RT.futurefuture<...>`).
This commit removes the mnenomics from the custom printers and thus causes them to emit the correct textual representation of types.
> fix(compiler): Do not print type mnenomic in custom printers for RT types

- ci/scripts/test_cml.sh
Now, you should not stumble on any flaky tests from our side
> chore(frontend): update cml test script to ignore flaky tests

- backends/concrete-cuda/implementation/include/bootstrap_multibit.h
- backends/concrete-cuda/implementation/include/linear_algebra.h
- backends/concrete-cuda/implementation/src/complex/operations.cuh
- backends/concrete-cuda/implementation/src/multiplication.cu
- backends/concrete-cuda/implementation/src/multiplication.cuh
- backends/concrete-cuda/implementation/test_and_benchmark/benchmark/benchmark_integer_multiplication.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/include/setup_and_teardown.h
- backends/concrete-cuda/implementation/test_and_benchmark/include/utils.h
- backends/concrete-cuda/implementation/test_and_benchmark/setup_and_teardown.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/test/test_integer_multiplication.cpp
- backends/concrete-cuda/implementation/test_and_benchmark/utils.cpp
- Add integer multiplication.
- Add full propagation inplace.
- Add tests and benchmarks. 
- Add structure for int mul radix ciphertexts
> feat(concrete-cuda): Integer multiplication, test and benchmark

- compilers/concrete-compiler/compiler/lib/Dialect/FHELinalg/IR/FHELinalgOps.cpp
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/ops.invalid.mlir
- compilers/concrete-compiler/compiler/tests/end_to_end_fixture/end_to_end_linalg_apply_lookup_table_gen.py
- compilers/concrete-compiler/compiler/tests/end_to_end_fixture/tests_cpu/end_to_end_fhelinalg.yaml
- compilers/concrete-compiler/compiler/tests/end_to_end_tests/end_to_end_jit_auto_parallelization.cc
Adds support for dynamic luts in the fhe linalg dialect.
> feat(compiler): adds support for dynamic luts in fhelinalg

- docs/SUMMARY.md
- docs/tutorial/workarounds.md
Add common FHE tricks from community answers
> docs(frontend): add FHE workarounds

- docs/tutorial/extensions.md
- frontends/concrete-python/concrete/fhe/extensions/hint.py
- frontends/concrete-python/examples/key-value-database/dynamic-size.py
- frontends/concrete-python/examples/key-value-database/static-size.py
- frontends/concrete-python/tests/mlir/test_converter.py
(closes https://github.com/zama-ai/concrete/issues/598)
> Fix: Key Value Database Example

- compilers/concrete-compiler/compiler/include/concretelang/Bindings/Python/CompilerEngine.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerEngine.cpp
- compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/client_support.py
- compilers/concrete-compiler/compiler/tests/end_to_end_fixture/tests_cpu/end_to_end_multi_ouput.yaml
- compilers/concrete-compiler/compiler/tests/python/test_client_server.py
- frontends/concrete-python/concrete/fhe/compilation/compiler.py
- frontends/concrete-python/tests/compilation/test_compiler.py
- frontends/concrete-python/tests/execution/test_multi_output.py
draft to close https://github.com/zama-ai/concrete-internal/issues/373
> feat(compiler): Support multi-output

- compilers/concrete-compiler/compiler/Makefile
Debug builds preserve assertions in libomp, which are implemented using code form libstdc++. However, the build rules for libomp explicitly prevent the library from being linked with libstdc++ by default, resulting in a linker error for debug builds.
This patch sets the option `LIBOMP_USE_STDCPPLIB` for libomp to `ON` for debug builds in order to force linking with libstdc++.
> fix(compiler): Force linking of libomp with libstdc++ in debug builds

- frontends/concrete-python/concrete/fhe/compilation/decorators.py
- frontends/concrete-python/concrete/fhe/mlir/converter.py
- frontends/concrete-python/concrete/fhe/mlir/processors/assign_bit_widths.py
- frontends/concrete-python/concrete/fhe/representation/graph.py
- frontends/concrete-python/concrete/fhe/tracing/typing.py
- frontends/concrete-python/tests/mlir/test_converter.py
…for being able to see the assigned bit-widths afterward
> feat(frontend/python): process graph in place before MLIR conversion

- docs/getting-started/fhe_basics.md
Same as #606 but with a fixed commit message
> chore(frontend-python): typo in fhe_basics.md

- frontends/concrete-python/tests/execution/test_others.py
This change is required because because inputset evaluation happens after fusing and this error was being raised during fusing. So it doesn't have the full bounds or the measured bit-width.
> fix(frontend-python): use more strict inputset to fix a flanky test

- README.md
Some minor changes for the README:
- make it more coherent with the Concrete ML readme
- remove the warning about the old library which was called Concrete
If we want to keep the warning, OK, but I think it could be ok now to move on, and clean a bit our README. CC @BourgerieQuentin @aquint-zama @zaccherinij
> docs(compiler): update the readme

- backends/concrete-cpu/implementation/Cargo.toml
- this will allow to have AVX512 on x86 machines which have the hardware feature available if concrete-cpu is built with a rust nightly toolchain and the nightly feature enabled
as discussed and as proposed by @bcm-at-zama I pushed this small fix to make the AVX512 feature from TFHE-rs available in concrete-cpu when the nightly feature is enbaled.
> chore(concrete_cpu): fix nightly feature which was not forwarded to TFHE-rs

- frontends/concrete-python/examples/game_of_life/game_of_life.py
Testing fhe.bits() within Game of Life
> chore: using fhe.bits() feature in Game of Life example

- compilers/concrete-compiler/compiler/README.md
> docs(compiler): fix readme

- frontends/concrete-python/concrete/fhe/mlir/converter.py
- frontends/concrete-python/concrete/fhe/mlir/processors/assign_bit_widths.py
- frontends/concrete-python/tests/mlir/test_converter.py
When using composition, ensures that inputs and outputs use the same bitwidth (for encoder compatibility).
> fix(frontend): fix composition bitwidth incompatibility

- compilers/concrete-compiler/compiler/CMakeLists.txt
When building the compiler in debug mode, builds the optimizer in debug mode as well. Makes it possible to step in optimizer code as well.
> chore(optimizer): allow debug mode compilation

- compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHE/IR/FHEOps.td
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHELinalg/IR/FHELinalgOps.td
- compilers/concrete-compiler/compiler/lib/Dialect/FHE/Analysis/ConcreteOptimizer.cpp
- compilers/concrete-compiler/compiler/tests/end_to_end_tests/end_to_end_jit_test.cc
- compilers/concrete-optimizer/concrete-optimizer-cpp/src/concrete-optimizer.rs
- compilers/concrete-optimizer/concrete-optimizer-cpp/src/cpp/concrete-optimizer.cpp
- compilers/concrete-optimizer/concrete-optimizer-cpp/src/cpp/concrete-optimizer.hpp
- compilers/concrete-optimizer/concrete-optimizer-cpp/tests/src/main.cpp
- compilers/concrete-optimizer/concrete-optimizer/src/dag/operator/operator.rs
- compilers/concrete-optimizer/concrete-optimizer/src/dag/rewrite/regen.rs
- compilers/concrete-optimizer/concrete-optimizer/src/dag/unparametrized.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/analyze.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/optimize/tests.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/partition_cut.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/partitionning.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/visualization.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/solo_key/analyze.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/solo_key/optimize.rs
In the optimizer, nodes without consumers are identified as outputs. Since we can now return multiple values, this is inherently buggy, since a value can then be both returned, and consumed to create another input.
This commit fixes this by allowing the compiler to tag nodes as being outputs.
> fix(optimizer): compiler output forwarding

- compilers/concrete-compiler/compiler/Makefile
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/context.h
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/dfr_tasks.hpp
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/distributed_generic_task_server.hpp
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/generated/dfr_task_work_function_calls.h
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/generated/generate_dfr_work_function_calls.sh
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/key_manager.hpp
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/workfunction_registry.hpp
- compilers/concrete-compiler/compiler/lib/Runtime/CMakeLists.txt
- compilers/concrete-compiler/compiler/lib/Runtime/DFRuntime.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/context.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/key_manager.cpp
- docker/Dockerfile.hpx-env
Add support for eager (default) and lazy (set DFR_LAZY_KEY_TRANSFER environment variable on/off) evaluation key transfers in multi-key distributed execution. 
This also bumps the HPX version from 1.7.1 to 1.9.1 as this fixes two bugs in program termination and in key transfer.
> Multi-key support for distributed execution

- compilers/concrete-compiler/compiler/lib/Dialect/FHE/Analysis/ConcreteOptimizer.cpp
The DAG pass establishing a mapping between operations in the IR and the optimizer DAG currently omits assignment of the optimizer ID to `FHE.reinterpret_precision` operations via the `TFHE.OId` attribute. This prevents subsequent passes from determining to which optimizer partition a `FHE.reinterpret_precision` operation belongs.
This commit removes the early exit in `FunctionToDag::addOperation` for the handling of `FHE.reinterpret_precision` that prevented the code assigning the optimizer ID from being executed.
> fix(compiler): Do not omit assignment of optimizer ID to FHE.reinterpret_precision

- docs/SUMMARY.md
- docs/core-features/table_lookups.md
Follow up with reviews of https://github.com/zama-ai/concrete/pull/723/files
closes #https://github.com/zama-ai/concrete-internal/issues/622
> docs(compiler): update the doc (Part 2) [ready to be reviewed]

- docs/core-features/rounding.md
> docs(compiler): fixing a bad char in the doc 

- .github/workflows/compiler_build_and_test_cpu_distributed.yml
- .github/workflows/main.yml
- ci/slab.toml
- compilers/concrete-compiler/compiler/Makefile
Add the distributed CI workflow and test target.
> Distributed CI

- compilers/concrete-compiler/compiler/lib/Conversion/FHETensorOpsToLinalg/TensorOpsToLinalg.cpp
- compilers/concrete-compiler/compiler/lib/Dialect/FHELinalg/Transforms/Tiling.cpp
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/tiling.mlir
Add support for tiling of:
* All element-wise ops
* All flavors of applications of lookup tables in FHELinalg
* All matmul operations
* `fhelinalg.sum`
* `fhelinalg.transpose`
* `fhelinalg.partition_frontier`
> Add support for tiling of more FHELinalg operations

- README.md
- docs/get-started/quick_start.md
Mainly, this PR is to unify examples in README and in quick_start.md, as requested by @yuxizama. 
closes zama-ai/concrete-internal#603
By the way, I used the opportunity to update a bit the example
- with no more hardcoded pairs (clearer inputset, clearer samples for execution)
- with an assert of the correct execution
I find this example easier to be reused for users (eg, me, each time, I apply this very same change). Is it ok with you?
> Uniformize examples readme and quickstart [ready for reviews]

- compilers/concrete-compiler/compiler/include/concretelang/Transforms/TypeInferenceRewriter.h
The type inference rewriter changes the name of the rewritten function to the name of the original function when the rewriting process is complete. However, the name is retrieved from the original function operation after the operation has already been replaced and thus destroyed, resulting in a null pointer dereference.
This change retrieves the name of the original function before it is replaced and saves it in a copy, which is then used to safely assign the new name to the rewritten function.
> fix(compiler): Type inference rewriter: Fix use-after-free in function renaming

- README.md
use Windows WSL instead
As decided in https://zama-ai.slack.com/archives/C0455QDGT6C/p1713430487282589 thread
> docs(compiler): Windows pip version will not exist

- compilers/concrete-compiler/compiler/include/concretelang/Transforms/TypeInferenceRewriter.h
Return-like operations require special treatment by the type inference rewriter, since their operand types are both tied to the result types of their producers and to result types of their parent operations.
The inference scheme for ordinary operations, in which the initial local inference state is composed of the operand types of the rewritten producers and the old types of related operations before rewriting is insufficient, since this may result in a mismatch between the inferred types and the actual types of the already rewritten parent operation.
Until now, precedence of the new result types of the parent operation has been implemented by simply designating these types as the operand types of a return-like operation. However, while this works as intended for return-like operations, …
> fix(compiler): Type inference rewriter: Handle return-like operations correctly

- compilers/concrete-compiler/compiler/lib/Dialect/RT/IR/RTDialect.cpp
The type parser of the RT dialect unconditionally attempts to parse the string "future". This breaks the parsing of any RT type. Remove unconditional parsing of this prefix.
> fix(compiler): Fix RT type parser: Remove unconditional parsing of prefix "future"

- frontends/concrete-python/concrete/fhe/compilation/server.py
We currently have something like `var = TemporaryDirectory` without explicitly calling the `close` method on `var` thus raising a `ResourceWarning` when the resource is implicitely cleaned-up.
This could be avoided by using `mkdtemp` instead.
> fix(frontend): remove `ResourceWarning` from using `TemporaryDirectory`

- compilers/concrete-compiler/compiler/lib/Dialect/RT/IR/RTDialect.cpp
- compilers/concrete-compiler/compiler/lib/Dialect/RT/Transforms/HoistAwaitFuturePass.cpp
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/RT/hoist_await_future_ivexpr.mlir
Until now, the pass hoisting `RT.await_future` operations only supports `tensor.parallel_insert_slice` operations that use loop induction variables directly as indexes. Any more complex indexing expressions produce a domination error, since a
`tensor.parallel_insert_slice` cloned by the pass into an additional parallel for loop is left with references to values from the original loop.
This change properly clones operations producing intermediate values within the original parallel for loop and thus adds support for indexing expressions that reference loops IVs only indirectly.
> fix(compiler): Support indirect references to IVs in indexes when hoisting RT.await_future ops

- compilers/concrete-compiler/compiler/include/concretelang/Dialect/FHELinalg/IR/FHELinalgOps.td
- compilers/concrete-compiler/compiler/lib/Dialect/FHELinalg/IR/FHELinalgOps.cpp
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/concat.invalid.mlir
- compilers/concrete-compiler/compiler/tests/check_tests/Dialect/FHELinalg/folding.mlir
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18dQsoRD9hv4NoTIheYaOsyxNW3BVajLY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=m7_dnfD)
> feat(compiler): Allow concat with only one operand

- .github/workflows/compiler_build_and_test_cpu_distributed.yml
Remove the whole concrete directory when cleaning the instance as lock files can persist after a failed run and block all subsequent runs. The instance is not regenerated each time as it needs to set up the cluster.
> fix(ci): [Distributed CI] 

- docs/SUMMARY.md
- docs/explanations/backends/README.md
- docs/explanations/backends/new_backend.md
- docs/explanations/layout.md
- There was an .md we had removed from GitBook, when we re-factorized: adding it again
- By the way, fixing a bit of typos
> Fixing doc

- compilers/concrete-compiler/compiler/include/concretelang/Runtime/context.h
- compilers/concrete-compiler/compiler/include/concretelang/ServerLib/ServerLib.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/context.cpp
- compilers/concrete-compiler/compiler/lib/ServerLib/ServerLib.cpp
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18BT3E1yLhRyHmr2bheDM9znenEjLYT6U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=kY75WIz)
close zama-ai/concrete-internal#704
> fix(compiler): Decompression of evaluation keys was done several times

- .github/workflows/concrete_python_release.yml
- we don't want one push failure to impact the others
- we want build failures to stop the push
> Python Realse CI Fixes

- compilers/concrete-compiler/compiler/include/concretelang/Common/Keys.h
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/context.h
- compilers/concrete-compiler/compiler/include/concretelang/ServerLib/ServerLib.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- compilers/concrete-compiler/compiler/lib/Common/Keys.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/context.cpp
- compilers/concrete-compiler/compiler/lib/ServerLib/ServerLib.cpp
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX186TyO9no6Jyjx8hkE3tLwEwetX26I5WPE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=uV2CJ3o)
This partially reverts commit 081e8b7b74d31909a3aa9a59099004a1ceeeae3f.
> fix(compiler): Share the decompress state instead of try to avoid copies

- README.md
- docs/get-started/installing.md
- frontends/concrete-python/README.md
make a note about the new Zama PyPI
> docs(frontend): update installation instructions

- .github/workflows/concrete_python_release.yml
nightly releases should now a more meaningful version format: MAJOR.MINOR.PATCH-devYEAR.MONTH.DAY
> chore(ci): version nightlies as prereleases

- docs/get-started/compatibility.md
- docs/get-started/installing.md
- docs/get-started/quick_start.md
- docs/get-started/readme.md
- docs/get-started/terminology.md
I've rephrased some sentences to increase the readability. Please check to ensure that my modification does not alter the technical implications. 
Feedback is welcomed!
> Docs language edit - Part 1

- docs/SUMMARY.md
- docs/core-features/minmax.md
- docs/core-features/non_linear_operations.md
- docs/core-features/table_lookups.md
- docs/core-features/table_lookups_advanced.md
- docs/dev/compilation/compiler_internals.md
Trying to:
- make the simple-user facing doc a bit shorter and simpler
- and move the complex parts to some power user doc
> docs(frontend): simplify the doc for the non-power user

- .github/workflows/refresh_zama_pypi.yml
This is needed in case manual changes are made. It will update html indexes and invalidate the cloudfront cache
> feat(ci): add manual workflow to refresh Zama PyPI

- docs/guides/configure.md
- frontends/concrete-python/concrete/fhe/compilation/circuit.py
- frontends/concrete-python/concrete/fhe/compilation/configuration.py
- frontends/concrete-python/concrete/fhe/compilation/module.py
- frontends/concrete-python/tests/compilation/test_circuit.py
- frontends/concrete-python/tests/compilation/test_modules.py
(closes https://github.com/zama-ai/concrete-internal/issues/734)
> feat(frontend-python): simulate encrypt run decrypt option

- docs/SUMMARY.md
- docs/compilation/common_errors.md
Adding a list of most common errors with CP. If ever you have other issues you would like to add, don't hesitate to do it or ask me to do it
closes #https://github.com/zama-ai/concrete-internal/issues/719
closes #https://github.com/zama-ai/concrete-internal/issues/508
closes #https://github.com/zama-ai/concrete-internal/issues/508
> docs(frontend): adding a section for most common errors

- .github/workflows/compiler_build_and_test_cpu_distributed.yml
Change location of key cache to avoid running out of disk space on compute nodes.
> Fix Distributed CI running out of disk space

- compilers/concrete-compiler/compiler/include/concretelang/Runtime/GPUDFG.hpp
- compilers/concrete-compiler/compiler/include/concretelang/Support/CompilerEngine.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/__init__.py
- compilers/concrete-compiler/compiler/lib/Runtime/CMakeLists.txt
- compilers/concrete-compiler/compiler/lib/Runtime/GPUDFG.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/context.cpp
- compilers/concrete-compiler/compiler/lib/Support/CompilerEngine.cpp
Ensure that the compiler/runtime have GPU capability and that at least one device is available to run on.
If the compiler/runtime was not compiled with Cuda enabled (e.g., a non-GPU wheel) and GPU support is requested (use_gpu) emit warning message and continue without GPU, using CPU only with loop parallelism.
If the compiler or wheel are GPU capable, but no GPU is found, emit warning and continue on CPU.
> Add sanity checks when GPU is requested

- frontends/concrete-python/examples/key-value-database/dynamic-size.py
- frontends/concrete-python/examples/key-value-database/static-size.py
(closes https://github.com/zama-ai/concrete/issues/865)
> feat(frontend-python): fix key value database example

- .github/workflows/concrete_python_release.yml
- create draft release only for public tag
- remove wheels from releases (only keep provenance file)
> chore(ci): create draft release only for public releases

- .github/workflows/compiler_publish_docker_images.yml
- ci/slab.toml
- compilers/concrete-compiler/compiler/lib/Runtime/context.cpp
- docker/Dockerfile.concrete-compiler-env
Github has deprecated Ubuntu18.04 aa some actions now require GLIBC version >= 2.28. This is not supported in Ubuntu18.04.
This PR changes the CI AMI for both Concrete compiler GPU build&test as well as for python GPU tests to a new AMI based on Ubuntu 22.04. 
It also fixes Docker image build which was also broken by Github updates.
> Fix GPU compiler CI and python GPU wheel tests

- .github/workflows/concrete_python_release_gpu.yml
- backends/concrete-cuda/implementation/src/bootstrap_amortized.cu
- backends/concrete-cuda/implementation/src/bootstrap_low_latency.cu
- backends/concrete-cuda/implementation/src/bootstrap_multibit.cu
- backends/concrete-cuda/implementation/src/crypto/bootstrapping_key.cuh
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/SDFG/CMakeLists.txt
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/SDFG/Transforms/CMakeLists.txt
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/SDFG/Transforms/Passes.h
- compilers/concrete-compiler/compiler/include/concretelang/Dialect/SDFG/Transforms/Passes.td
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/stream_emulator_api.h
- compilers/concrete-compiler/compiler/include/concretelang/Runtime/time_util.h
- compilers/concrete-compiler/compiler/lib/Conversion/SDFGToStreamEmulator/SDFGToStreamEmulator.cpp
- compilers/concrete-compiler/compiler/lib/Dialect/SDFG/Transforms/CMakeLists.txt
- compilers/concrete-compiler/compiler/lib/Dialect/SDFG/Transforms/SDFGBufferOwnership.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/CMakeLists.txt
- compilers/concrete-compiler/compiler/lib/Runtime/DFRuntime.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/GPUDFG.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/time_util.cpp
- compilers/concrete-compiler/compiler/lib/Runtime/wrappers.cpp
- compilers/concrete-compiler/compiler/lib/Support/CompilerEngine.cpp
- compilers/concrete-compiler/compiler/lib/Support/Pipeline.cpp
This PR reduces the number of copy operations by transferring ownership of data buffers to the runtime system, and by merging the outputs of SDFG compute graphs in place. 
It also fixes some bugs and minor issues.
> GPU runtime optimisation

- docs/tutorials/see-all-tutorials.md
- frontends/concrete-python/examples/levenshtein_distance/levenshtein_distance.md
- frontends/concrete-python/examples/levenshtein_distance/levenshtein_distance.py
Adding a use-case for Levenshtein distance
closes #https://github.com/zama-ai/concrete-internal/issues/750
> docs(frontend): adding a use-case for Levenshtein distance

- docs/compilation/common_errors.md
- docs/get-started/installing.md
closes #https://github.com/zama-ai/concrete-internal/issues/770
> docs(frontend): more info on where to find wheels

- ci/slab.toml
- compilers/concrete-compiler/compiler/lib/Runtime/GPUDFG.cpp
- compilers/concrete-compiler/compiler/lib/Support/CompilerEngine.cpp
-- and fix regressions introduced post v2.7.0 which were not visible due to the broken CI.
> Fix GPU python wheel CI 

- compilers/concrete-compiler/compiler/tests/check_tests/Transforms/scf-to-parallel.mlir
This ensures that the regression fixed by
3cd3dff92a37afb1ec6d5a6dbb5c3b80d6035572 is not reintroduced, which caused the compiler to abort in `ForLoopToParallelPass` for `scf.for` loops with iteration arguments, even if these were marked with the attribute `parallel` set to `false`.
> test(compiler): Ensure that ForLoopToParallelPass does not trigger for scf.for with parallel = false

- .github/workflows/main.yml
- compilers/concrete-compiler/compiler/lib/Dialect/FHE/Analysis/ConcreteOptimizer.cpp
note: this cannot be done as before in the optimizer since the latter had more information. here we assumed each input contribute equally to the resulting noise.
A better fix could be to provide the linear relation of inputs instead of manp and smanp.
> fix(compiler): levelledOP conversion to dot like for optimizer

- docs/tutorials/see-all-tutorials.md
- frontends/concrete-python/examples/floating_point/floating_point.ipynb
Adding a tutorial, to answer common questions about "how to deal with floats in CP"
closes https://github.com/zama-ai/concrete-internal/issues/744
> docs(compiler): adding a tutorial with floats

- compilers/concrete-optimizer/concrete-optimizer/src/dag/operator/operator.rs
- compilers/concrete-optimizer/concrete-optimizer/src/dag/rewrite/regen.rs
- compilers/concrete-optimizer/concrete-optimizer/src/dag/unparametrized.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/analyze.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/operations_value.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/optimize/mod.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/optimize/tests.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/partition_cut.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/partitionning.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/partitions.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/symbolic_variance.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/solo_key/analyze.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/decomposition/cmux.rs
- compilers/concrete-optimizer/concrete-optimizer/src/utils/viz.rs
- Add a change_partition operator to manually go from one partition to the other. We currently allow to specify both partitions, but our main usecase would only require setting one of them.
- Take into account external partitions during partitioning and optim
> [Optimizer] support external partitions

- compilers/concrete-optimizer/concrete-optimizer-cpp/src/concrete-optimizer.rs
revert #991 due to https://github.com/zama-ai/concrete/actions/runs/10385798019/job/28755712025
> Revert "fix(optimizer): remove hardcoded processing unit"

- README.md
- docs/README.md
- docs/core-features/table_lookups.md
- docs/get-started/quick_start.md
- docs/tutorials/see-all-tutorials.md
Promote the developer survey in the doc to gather developer feedbacks.
> docs(frontend): add developer survey

- frontends/concrete-python/examples/levenshtein_distance/IBAN_name_check.ipynb
- frontends/concrete-python/examples/levenshtein_distance/README.md
- frontends/concrete-python/examples/levenshtein_distance/levenshtein_distance.py
We have discussed with @GBAZama that it may be useful to show how to do IBAN name comparisons with Concrete. Let me try a small notebook which does that, feedback is welcome!
> docs(frontend): adding a use-case for fuzzy encrypted name comparison

- docs/SUMMARY.md
- docs/explanations/releasing.md
closes https://github.com/zama-ai/concrete-internal/issues/759
> docs(compiler): add releasing process

- docs/compilation/composing_functions_with_modules.md
There is two mistakes in the Modules doc, if I am not wrong. Could you check @aPere3 ?
> fix(frontend): fixing typos in the documentation

- docs/execution-analysis/formatting_and_drawing.md
- docs/execution-analysis/gpu_acceleration.md
- docs/guides/configure.md
(Sorry I didn't mean to make a long PR, I didn't expect the "configure" one would be so long. )
In Configure, I mainly changed the format to replace bullet points with H4 titles and reordered the options alphabetically, without rewordings.  I think the new format would make it easier for users to quickly find what they need on the page.
> Doc edits: Formatting and Configure

- docs/optimization/improve-parallelism/self.md
I saw this link being fragile in several links checks in our build, eg https://github.com/zama-ai/concrete/actions/runs/10593785720/job/29356040165?pr=1022
> docs(frontend): disable a link check which is too flaky

- frontends/concrete-python/concrete/fhe/mlir/context.py
- frontends/concrete-python/tests/mlir/test_converter.py
The issue was that we consider clear values as signed, so if one were to do, `x @ y` where x is encrypted uintx and y is clear uinty, x would be converted to signed, which is not necessary.
> fix(frontend): remove unnecessary signed conversions

- docs/tutorials/see-all-tutorials.md
- frontends/concrete-python/examples/pir/PIR.ipynb
- frontends/concrete-python/examples/pir/README.md
Work in progress, I've made experiments for PIR with Concrete. I think we can find use-cases for which it's not that bad.
> docs(frontend): adding a use-case for private information retrieval

- .github/workflows/compiler_publish_docker_images.yml
from the docs: The jobs.<job_id>.if condition is evaluated before jobs.<job_id>.strategy.matrix is applied. So we can't just use matrix.dockerfile so we have to build both images if one of the two files change, or we will have to split this into two.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif
> perf(ci): avoid building cuda image everytime

- .github/workflows/docker-lint.yml
- .hadolint.yaml
- docker/Dockerfile.concrete-compiler-env
- docker/Dockerfile.concrete-python
- docker/Dockerfile.cuda-118-env
- docker/Dockerfile.cuda-123-env
- docker/Dockerfile.hpx-env
This adds hadolint linter for all current dockerfiles.
- New dockerfiles should be added to the workflow for linting
- CI fail if any rule is violated (I linted everything so it's green now)
- Exceptions can be made using `# hadolint ignore=DLXXXX`
> feat(ci): lint dockerfiles using hadolint

- backends/concrete-cpu/implementation/include/concrete-cpu.h
- backends/concrete-cpu/implementation/src/c_api/fheint.rs
- compilers/concrete-compiler/compiler/include/concretelang/ClientLib/ClientLib.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- compilers/concrete-compiler/compiler/lib/Bindings/Python/concrete/compiler/tfhers_int.py
- compilers/concrete-compiler/compiler/lib/ClientLib/ClientLib.cpp
- frontends/concrete-python/concrete/fhe/mlir/converter.py
- frontends/concrete-python/concrete/fhe/tfhers/bridge.py
- frontends/concrete-python/concrete/fhe/tfhers/dtypes.py
- frontends/concrete-python/tests/execution/test_tfhers.py
- frontends/concrete-python/tests/tfhers-utils/src/main.rs
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX11Ddfi4Eb4ePFAzDLbTsqniEBK21bBks%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vmmdSW9)
> feat(frontend/compiler): support TFHErs fheint8

- .github/workflows/concrete_python_release.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19DthMgb7du4Vett2Dwkdz3bNOQeiuqxD4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tdmeVHs)
> chore(ci): Remove release-checks for pushing releases on private pypi

- .github/actionlint.yml
- .github/actions/optimizer_setup/action.yml
- .github/actions/setup_rust_toolchain_for_concrete_cpu/action.yml
- .github/workflows/concrete_compiler_benchmark.yml
- .github/workflows/concrete_compiler_test_cpu.yml
- .github/workflows/concrete_compiler_test_cpu_distributed.yml
- .github/workflows/concrete_compiler_test_macos_cpu.yml
- .github/workflows/concrete_ml_test.yml
- .github/workflows/concrete_optimizer.yml
- .github/workflows/concrete_python_benchmark.yml
- .github/workflows/concrete_python_finalize_release.yml
- .github/workflows/concrete_python_release_cpu.yml
- .github/workflows/concrete_python_release_gpu.yml
- .github/workflows/concrete_python_test_gpu_wheel.yml
- .github/workflows/concrete_python_test_macos.yml
- .github/workflows/docker_compliance.yml
- .github/workflows/ml_benchmark_subset.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1wY1VgS4kMb81YsyaYW1kHSPbinvux2jI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=TzMsL3h)
> chore(ci): Fix actionlint

- .github/workflows/concrete_python_release_cpu.yml
- .github/workflows/concrete_python_test_macos.yml
- .github/workflows/scripts/fix_multi_omp_bug_macos.sh
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18TNnw9as8ykVXYPYpyPEl4nEtuLpcgBnY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=eQ3ugnU)
> Fix test macos

- .github/workflows/concrete_python_release_cpu.yml
- ci/slab.toml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX10GqBdTBU1Wh1zUZCjcDc8dvFVPwFxdt0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=g_KLo1H)
some steps using the release profile were requiring root privileges
> fix(ci): setup HOME manually instead of changing user

- .github/workflows/concrete_compiler_test_macos_cpu.yml
- .github/workflows/concrete_python_release_cpu.yml
- .github/workflows/concrete_python_test_macos.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Inb91z3FygmzGiwB5jLs4oKU9X9z0g%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=qwCo_4y)
the notification action can't run on Mac https://github.com/rtCamp/action-slack-notify/issues/22
> fix(ci): notify on MacOS failures

- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- frontends/concrete-python/concrete/fhe/compilation/keys.py
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18Yx3uc59JEPsG0hmQmVNhRuUg7CO7Q%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=enpFIW8)
reduce memory usage by avoiding unecessary copy
> perf(frontend/compiler): deser keyset using path instead of buffer

- compilers/concrete-optimizer/concrete-optimizer-cpp/src/concrete-optimizer.rs
- compilers/concrete-optimizer/concrete-optimizer/src/dag/unparametrized.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/analyze.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/keys_spec.rs
- compilers/concrete-optimizer/concrete-optimizer/src/optimization/dag/multi_parameters/optimize/restriction.rs
- compilers/concrete-optimizer/concrete-optimizer/src/utils/viz.rs
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Bw3LG29fyybHsZ5uWNzOUUwDX6UhYJf4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=j52zE8m)
> chore(optimizer): Update linting

- docs/compilation/composing_functions_with_modules.md
Combined with `inputset = list(range(20))` below current example leads to bugs due to the expression evaluation order
> Fix docs to properly limit variable size

- compilers/concrete-compiler/compiler/include/concretelang/Common/Keys.h
- compilers/concrete-compiler/compiler/include/concretelang/Common/Keysets.h
- compilers/concrete-compiler/compiler/include/concretelang/Common/Protocol.h
- compilers/concrete-compiler/compiler/include/concretelang/Common/Values.h
- compilers/concrete-compiler/compiler/include/concretelang/TestLib/TestProgram.h
- compilers/concrete-compiler/compiler/lib/Bindings/Python/CompilerAPIModule.cpp
- compilers/concrete-compiler/compiler/lib/ClientLib/ClientLib.cpp
- compilers/concrete-compiler/compiler/lib/Common/Keys.cpp
- compilers/concrete-compiler/compiler/lib/Common/Keysets.cpp
- compilers/concrete-compiler/compiler/lib/Common/Protocol.cpp
- compilers/concrete-compiler/compiler/lib/Common/Transformers.cpp
- compilers/concrete-compiler/compiler/lib/Common/Values.cpp
- compilers/concrete-compiler/compiler/lib/ServerLib/ServerLib.cpp
- compilers/concrete-compiler/compiler/lib/Support/CompilationFeedback.cpp
- compilers/concrete-compiler/compiler/lib/Support/ProgramInfoGeneration.cpp
- frontends/concrete-python/concrete/fhe/compilation/keys.py
- frontends/concrete-python/tests/compilation/test_keys.py
Readers were automatically casted to Messages which cost a memory copy. It's now required to explicitly make this conversion (copy).
> Reduce memory copies of serialized buffers

- .github/workflows/concrete_compiler_benchmark.yml
- .github/workflows/concrete_compiler_publish_docker_images.yml
- .github/workflows/concrete_compiler_test_cpu.yml
- .github/workflows/concrete_compiler_test_cpu_distributed.yml
- .github/workflows/concrete_compiler_test_gpu.yml
- .github/workflows/concrete_ml_test.yml
- .github/workflows/concrete_python_benchmark.yml
- .github/workflows/concrete_python_release_cpu.yml
- .github/workflows/concrete_python_release_gpu.yml
- .github/workflows/concrete_python_tests_linux.yml
This reverts commit ef49513f85a5065634fa602b14b57e66e3c3de76.
> chore(ci): bump zama-ai/slab-github-runner from 1.2.0 to 1.4.0, revert

- .github/workflows/concrete_compiler_test_cpu_distributed.yml
there was no teardown at the end, but the instance was actually started and stopped at the end.
> chore(ci): rename steps to more meaningful names

- docs/dev/api/README.md
- docs/dev/api/concrete.fhe.tfhers.md
- frontends/concrete-python/concrete/fhe/tfhers/__init__.py
- frontends/concrete-python/examples/tfhers-ml/example.py
- frontends/concrete-python/tests/dtypes/test_tfhers.py
Adds the option to make a TFHErs integer datatype from a dict, in addition to the existing functionality which does the same but from a file containing a json.
> chore: add load tfhers params from dict

- .github/workflows/concrete_cpu_test.yml
- backends/concrete-cpu/implementation/cbindgen.toml
- backends/concrete-cpu/implementation/include/concrete-cpu.h
- backends/concrete-cpu/implementation/src/c_api/fheint.rs
- compilers/concrete-compiler/compiler/lib/ClientLib/ClientLib.cpp
- docs/dev/api/concrete.fhe.compilation.configuration.md
- docs/dev/api/concrete.fhe.mlir.context.md
- frontends/concrete-python/concrete/fhe/compilation/configuration.py
- frontends/concrete-python/concrete/fhe/mlir/context.py
- frontends/concrete-python/concrete/fhe/mlir/converter.py
- frontends/concrete-python/tests/execution/test_bit_extraction.py
- frontends/concrete-python/tests/execution/test_tfhers.py
- Support arbitrary bitwidth during native->TFHE-rs conversion (TFHE-rs need to be bigger than native however)
> TFHE-rs interop support more conversions

- docs/dev/api/README.md
- docs/dev/api/concrete.fhe.compilation.module.md
- docs/dev/api/concrete.fhe.compilation.server.md
- docs/dev/api/concrete.fhe.compilation.specs.md
- docs/dev/api/concrete.fhe.md
- docs/dev/api/concrete.fhe.tfhers.bridge.md
- docs/dev/api/concrete.fhe.tfhers.dtypes.md
- docs/dev/api/concrete.fhe.tfhers.md
- docs/dev/api/concrete.fhe.tfhers.specs.md
- frontends/concrete-python/concrete/fhe/compilation/module.py
- frontends/concrete-python/concrete/fhe/compilation/server.py
- frontends/concrete-python/concrete/fhe/compilation/specs.py
- frontends/concrete-python/concrete/fhe/tfhers/__init__.py
- frontends/concrete-python/concrete/fhe/tfhers/bridge.py
- frontends/concrete-python/concrete/fhe/tfhers/dtypes.py
- frontends/concrete-python/concrete/fhe/tfhers/specs.py
- frontends/concrete-python/tests/execution/test_tfhers.py
The serialization format for ClientSpec has changed and isn't backward compatible. @BourgerieQuentin do you think it's worth adding checks for older version and using old format in that case? I think we would have to bump MAJOR if we don't add checks and make it backward compatible.
EDIT:
Switched to a serialization that consider programinfo as Json so we embed tfhers_specs within it. This should be backward compatible.
> feat(frontend): extend bridge to work with Client

- .github/workflows/concrete_python_tests_linux.yml
I thought the image was already fixed and built, but it's not the case, so we will have to wait until it's done and we can rerun the CI and merge when it passes CP pytest
> chore(ci): remove capnp installation now available in docker image

- .github/workflows/concrete_python_release.yml
The tests are taking too long and we need to investigate why. We disable the full matrix in the meantime
> chore(ci): test single wheel in nightly release

- frontends/concrete-rust/concrete-keygen/Cargo.toml
cli bins require some optional packages that are only available when using the cli feature
> fix(frontend/rust): don't build cli bins if not instructed

- docs/dev/api/concrete.fhe.mlir.converter.md
- frontends/concrete-python/concrete/fhe/mlir/converter.py
- frontends/concrete-python/tests/execution/test_tfhers.py
We were previously setting the padding bit only, but this doesn't set the correct value if the native bitwidth is larger than the tfhers one. We need to extend the sign bit to any new msb + the padding bit.
> fix(frontend/py): extend sign bit in tfhers.to_native
